# -*- coding: utf-8 -*-
import csv

def get_data():
    rows = []
    
    # ---------------- VIAJES ----------------
    v_l1 = ["Avión", "Barco", "Tren", "Auto", "Bus", "Bicicleta", "Caminando", "Moto", "Taxi", "Uber", "Metro", "Subte", "Crucero", "Velero", "Lancha", "Canoa", "Jet", "Globo", "Helicóptero", "Cohete", "Maleta", "Mochila", "Bolso", "Cartera", "Pasaporte", "Visa", "DNI", "Pasaje", "Ticket", "Boleto", "Mapa", "Brújula", "GPS", "Hotel", "Hostel", "Carpa", "Camping", "Playa", "Montaña", "Bosque", "Selva", "Desierto", "Ciudad", "Pueblo", "Campo", "Isla", "Lago", "Río", "Mar", "Océano", "Pileta", "Sol", "Lluvia", "Nieve", "Viento", "Calor", "Frío", "Verano", "Invierno", "Otoño", "Primavera", "Turista", "Guía", "Camara", "Foto", "Video", "Recuerdo", "Souvenir", "Regalo", "Postal", "Carta", "Email", "Wifi", "Roaming", "Chip", "Cargador", "Adaptador", "Enchufe", "Batería", "Lentes", "Gorra", "Sombrero", "Protector", "Bronceador", "Toalla", "Biquini", "Malla", "Ojotas", "Sandalias", "Zapatillas", "Botas", "Campera", "Bufanda", "Guantes", "Paraguas", "Piloto", "Valija", "Ruedas", "Aeropuerto", "Puerto"]
    v_l1_en = ["Plane", "Boat", "Train", "Car", "Bus", "Bike", "Walking", "Moto", "Taxi", "Uber", "Subway", "Metro", "Cruise", "Sailboat", "Speedboat", "Canoe", "Jet", "Balloon", "Helicopter", "Rocket", "Suitcase", "Backpack", "Bag", "Wallet", "Passport", "Visa", "ID", "Ticket", "Pass", "Stub", "Map", "Compass", "GPS", "Hotel", "Hostel", "Tent", "Camping", "Beach", "Mountain", "Forest", "Jungle", "Desert", "City", "Town", "Farm", "Island", "Lake", "River", "Sea", "Ocean", "Pool", "Sun", "Rain", "Snow", "Wind", "Heat", "Cold", "Summer", "Winter", "Autumn", "Spring", "Tourist", "Guide", "Camera", "Photo", "Video", "Memory", "Souvenir", "Gift", "Postcard", "Letter", "Email", "Wifi", "Roaming", "Sim", "Charger", "Adapter", "Plug", "Battery", "Glasses", "Cap", "Hat", "Sunscreen", "Tanning", "Towel", "Bikini", "Swimsuit", "Flipflops", "Sandals", "Sneakers", "Boots", "Jacket", "Scarf", "Gloves", "Umbrella", "Raincoat", "Luggage", "Wheels", "Airport", "Port"]

    while len(v_l1) < 100: v_l1.append("Viaje Extra L1 " + str(len(v_l1)))
    while len(v_l1_en) < 100: v_l1_en.append("Travel Extra L1 " + str(len(v_l1_en)))
    v_l1 = v_l1[:100]; v_l1_en = v_l1_en[:100]

    for i in range(100): rows.append(["Viajes", "Baja", v_l1[i], v_l1_en[i]])
    
    v_l2 = ["Hacer valija", "Perder vuelo", "Tomar taxi", "Esperar bus", "Comprar pasaje", "Hacer checkin", "Pasar aduana", "Mostrar pasaporte", "Sacar foto", "Filmar video", "Comer raro", "Probar comida", "Dormir hotel", "Armar carpa", "Prender fuego", "Nadar mar", "Subir montaña", "Caminar mucho", "Alquilar auto", "Manejar ruta", "Poner nafta", "Pagar peaje", "Perderse calle", "Pedir ayuda", "Leer mapa", "Usar traductor", "Hablar idioma", "Comprar regalo", "Mandar postal", "Llamar casa", "Extrañar casa", "Conocer gente", "Hacer amigos", "Bailar noche", "Tomar trago", "Broncearse sol", "Quemar piel", "Poner crema", "Usar lentes", "Perder lentes", "Perder gorra", "Romper ojota", "Llenar arena", "Sacudir toalla", "Cruzar calle", "Subir metro", "Bajar subte", "Esperar tren", "Correr tren", "Perder tren", "Vuelo demorado", "Maleta perdida", "Valija rota", "Olvidar cargador", "Sin batería", "Sin señal", "Sin wifi", "Buscar baño", "Pagar baño", "Cambiar plata", "Usar tarjeta", "Sacar plata", "Contar monedas", "Dejar propina", "Quejarse precio", "Regatear", "Comprar barato", "Comprar caro", "Ser estafado", "Perder billetera", "Perder celular", "Encontrar algo", "Ver museo", "Entrar iglesia", "Ver estatua", "Caminar puente", "Cruzar río", "Navegar barco", "Marearse barco", "Vomitar bolsa", "Dormir avión", "Ver película", "Leer guía", "Preguntar calle", "Seguir guía", "Ir excursión", "Sacar entrada", "Hacer fila", "Esperar turno", "Entrar gratis", "Colarse fila", "Correr lluvia", "Mojarse todo", "Secarse sol", "Tener frío", "Tener calor", "Sudar mucho", "Caminata larga"]
    v_l2_en = ["Packing bags", "Missing flight", "Taking taxi", "Waiting bus", "Buying ticket", "Checking in", "Customs pass", "Show passport", "Taking photo", "Filming video", "Eating weird", "Tasting food", "Hotel sleep", "Pitching tent", "Lighting fire", "Sea swim", "Climbing mt", "Walking lot", "Renting car", "Driving road", "Gas fill", "Paying toll", "Getting lost", "Asking help", "Reading map", "Translator use", "Speaking lang", "Buying gift", "Sending card", "Calling home", "Missing home", "Meeting ppl", "Making friends", "Night dance", "Drinking drink", "Suntanning", "Sunburning", "Cream apply", "Glasses use", "Losing glasses", "Losing cap", "Flipflop break", "Sand everywhere", "Shaking towel", "Crossing street", "Subway enter", "Subway exit", "Waiting train", "Running train", "Missing train", "Flight delayed", "Luggage lost", "Broken bag", "Forgot charger", "No battery", "No signal", "No wifi", "Finding WC", "Paying WC", "Change money", "Using card", "Withdraw cash", "Counting coins", "Leaving tip", "Price complain", "Haggling", "Buying cheap", "Buying exp", "Getting scammed", "Losing wallet", "Losing phone", "Finding item", "Museum visit", "Church enter", "Statue view", "Bridge walk", "River cross", "Boat sailing", "Seasickness", "Bag vomit", "Plane sleep", "Movie watch", "Guide reading", "Asking street", "Follow guide", "Tour going", "Ticket buy", "Queuing up", "Waiting turn", "Free entry", "Cutting line", "Rain run", "Getting soaked", "Sun drying", "Being cold", "Being hot", "Sweating lot", "Long walk"]

    while len(v_l2) < 100: v_l2.append("Viaje Extra L2 " + str(len(v_l2)))
    while len(v_l2_en) < 100: v_l2_en.append("Travel Extra L2 " + str(len(v_l2_en)))
    v_l2 = v_l2[:100]; v_l2_en = v_l2_en[:100]

    for i in range(100): rows.append(["Viajes", "Media", v_l2[i], v_l2_en[i]])
    
    v_l3 = ["Avión turbulencia miedo", "Maleta rueda rota", "Olvidar pasaporte casa", "Perder vuelo conexión", "Dormir piso aeropuerto", "Hotel cama chinches", "Ducha agua fría", "Desayuno feo hotel", "Dolor panza comida", "Vomitar en bus", "Mareo barco fuerte", "Perderse en selva", "Mosquitos pican todo", "Quemadura sol roja", "Arena en comida", "Robo cámara foto", "Estafa taxi caro", "Idioma nadie entiende", "Pedir comida error", "Comer bicho error", "Baño sucio ruta", "Sin papel baño", "Sin agua potable", "Comprar agua cara", "Perder grupo tour", "Guía aburrido habla", "Museo cerrado lunes", "Lluvia todo el viaje", "Nieve bloquea ruta", "Viento vuela carpa", "Auto alquilado choca", "Multa tráfico otro país", "Policía pide soborno", "Perder tarjeta crédito", "Cajero traga tarjeta", "Sin plata efectivo", "Cambio moneda malo", "Souvenir rompe valija", "Regalo feo familia", "Olvidar regalo alguien", "Llegar casa sin llave", "Vecino regó plantas", "Plantas muertas vuelta", "Mascota enojada vuelta", "Heladera podrida casa", "Jetlag no dormir", "Dormir reunión trabajo", "Extrañar vacaciones", "Querer volver viaje", "Odiar rutina vuelta", "Ver fotos llorar", "Tarjeta memoria llena", "Batería muere foto", "Cargador explota", "Enchufe no entra", "Adaptador olvidado", "Ropa sucia olor", "Valija no cierra", "Pagar exceso peso", "Sentarse separado avión", "Bebé llora vuelo", "Comida avión fea", "Café vuelca pantalón", "Azafata enojada", "Piloto habla raro", "Aterrizaje forzoso susto", "Aplaudir aterrizaje", "Perder bus salida", "Correr terminal bolso", "Caerse escalera mecánica", "Traabarse puerta giratoria", "Chocar vidrio hotel", "Resbalar borde pileta", "Tragar agua mar", "Medusa pica pierna", "Cangrejo muerde dedo", "Arena ojo molesta", "Gaviota roba comida", "Mono roba lentes", "Perro muerde pantalón", "Pisar caca calle", "Zapato roto caminar", "Ampollas pies dolor", "Mochila muy pesada", "Espalda duele cama", "Roncar hostel molesta", "Vecino ruidoso hotel", "Fiesta no deja dormir", "Alarma suena error", "Despertar tarde tour", "Perder barco isla", "Quedarse varado", "Pedir dedo ruta", "Caminar bajo lluvia", "Paraguas viento rompe", "Mojarse pies frío", "Resfriarse viaje", "Tener fiebre hotel"]
    v_l3_en = ["Plane turbulence fear", "Suitcase wheel break", "Forgot passport home", "Miss connection flight", "Airport floor sleep", "Hotel bed bugs", "Cold shower water", "Bad hotel breakfast", "Stomach ache food", "Bus vomit", "Seasick bad", "Lost in jungle", "Mosquito bites all", "Sunburn red skin", "Sand in food", "Camera theft", "Taxi scam price", "Language barrier bad", "Ordering food wrong", "Eating bug error", "Dirty toilet road", "No toilet paper", "No potable water", "Expensive water buy", "Lost tour group", "Boring guide talks", "Museum closed mon", "Rain all trip", "Snow block road", "Wind blows tent", "Rental car crash", "Traffic fine foreign", "Cop asks bribe", "Lost credit card", "ATM eats card", "No cash money", "Bad exchange rate", "Souvenir break bag", "Ugly family gift", "Forgot gift someone", "Home no key", "Neighbor watered plants", "Dead plants return", "Angry pet return", "Rotten fridge home", "Jetlag no sleep", "Sleep work meeting", "Miss vacation", "Want go back", "Hate routine back", "Cry looking photos", "Memory card full", "Battery die photo", "Charger explode", "Plug wont fit", "Adapter forgotten", "Dirty clothes smell", "Bag wont close", "Pay excess weight", "Sit separate plane", "Baby cry flight", "Bad plane food", "Coffee spill pants", "Angry stewardess", "Pilot weird talk", "Hard landing scare", "Clap landing", "Miss bus exit", "Run terminal bag", "Escalator fall", "Stuck revolving door", "Hit hotel glass", "Slip pool edge", "Swallow sea water", "Jellyfish sting leg", "Crab bite finger", "Sand eye hurt", "Seagull steal food", "Monkey steal glasses", "Dog bite pants", "Step poop street", "Shoe broken walk", "Blisters feet pain", "Backpack too heavy", "Back pain bed", "Snore hostel annoy", "Loud neighbor hotel", "Party no sleep", "Alarm ring error", "Wake late tour", "Miss boat island", "Stranded island", "Hitchhike road", "Walk in rain", "Umbrella wind break", "Wet cold feet", "Cold sickness trip", "Fever hotel bed"]

    while len(v_l3) < 100: v_l3.append("Viaje Extra L3 " + str(len(v_l3)))
    while len(v_l3_en) < 100: v_l3_en.append("Travel Extra L3 " + str(len(v_l3_en)))
    v_l3 = v_l3[:100]; v_l3_en = v_l3_en[:100]

    for i in range(100): rows.append(["Viajes", "Alta", v_l3[i], v_l3_en[i]])

    # ---------------- SORPRESA ----------------
    s_l1 = ["Regalo", "Fiesta", "Grito", "Susto", "Miedo", "Risa", "Llanto", "Abrazo", "Beso", "Carta", "Email", "Noticia", "Bebé", "Casamiento", "Viaje", "Premio", "Lotería", "Dinero", "Cheque", "Trabajo", "Despido", "Ascenso", "Renuncia", "Mudanza", "Visita", "Amigo", "Perro", "Gato", "Auto", "Casa", "Anillo", "Propuesta", "Divorcio", "Examen", "Nota", "Gol", "Campeón", "Perdedor", "Clima", "Lluvia", "Nieve", "Sol", "Arcoiris", "Eclipse", "Terremoto", "Incendio", "Accidente", "Choque", "Caída", "Golpe", "Corte", "Sangre", "Curita", "Hospital", "Doctor", "Enfermera", "Policía", "Ladrón", "Multa", "Juicio", "Carcel", "Libertad", "Fuga", "Escondida", "Juego", "Truco", "Magia", "Conejo", "Paloma", "Carta", "Moneda", "Fantasma", "Ovni", "Alien", "Monstruo", "Zombie", "Vampiro", "Bruja", "Hada", "Duende", "Dragón", "Unicornio", "Sirena", "Tesoro", "Mapa", "Isla", "Barco", "Avión", "Dron", "Robot", "Futuro", "Pasado", "Historia", "Secreto", "Mentira", "Verdad", "Chisme", "Rumor"]
    s_l1_en = ["Gift", "Party", "Scream", "Scare", "Fear", "Laugh", "Cry", "Hug", "Kiss", "Letter", "Email", "News", "Baby", "Wedding", "Trip", "Prize", "Lottery", "Money", "Check", "Job", "Firing", "Promotion", "Quitting", "Move", "Visit", "Friend", "Dog", "Cat", "Car", "House", "Ring", "Proposal", "Divorce", "Exam", "Grade", "Goal", "Champ", "Loser", "Weather", "Rain", "Snow", "Sun", "Rainbow", "Eclipse", "Quake", "Fire", "Crash", "Accident", "Fall", "Hit", "Cut", "Blood", "Bandaid", "Hospital", "Doctor", "Nurse", "Police", "Thief", "Fine", "Trial", "Jail", "Freedom", "Escape", "Hide", "Game", "Trick", "Magic", "Rabbit", "Dove", "Card", "Coin", "Ghost", "UFO", "Alien", "Monster", "Zombie", "Vampire", "Witch", "Fairy", "Elf", "Dragon", "Unicorn", "Mermaid", "Treasure", "Map", "Island", "Boat", "Plane", "Drone", "Robot", "Future", "Past", "History", "Secret", "Lie", "Truth", "Gossip", "Rumor"]
    
    while len(s_l1) < 100: s_l1.append("Sorpresa Extra " + str(len(s_l1)))
    while len(s_l1_en) < 100: s_l1_en.append("Surprise Extra " + str(len(s_l1_en)))
    s_l1 = s_l1[:100]; s_l1_en = s_l1_en[:100]

    for i in range(100): rows.append(["Sorpresa", "Baja", s_l1[i], s_l1_en[i]])

    s_l2 = ["Abrir caja", "Romper papel", "Leer carta", "Ver mensaje", "Atender teléfono", "Abrir puerta", "Encender luz", "Apagar luz", "Cerrar ojos", "Pedir deseo", "Soplar vela", "Cortar torta", "Brindar copa", "Tirar arroz", "Tirar ramo", "Agarrar ramo", "Sacar anillo", "Arrodillarse", "Decir sí", "Decir no", "Llorar emoción", "Reír nervios", "Gritar gol", "Saltar alegría", "Correr abrazo", "Besar boca", "Dar cachetada", "Tirar agua", "Mojar todo", "Ensucia ropa", "Romper vaso", "Caer piso", "Resbalar", "Tropezar", "Chocar", "Perder algo", "Encontrar algo", "Ver fantasma", "Oír ruido", "Oler feo", "Oler rico", "Comer algo", "Probar gusto", "Quemar lengua", "Morder lengua", "Pinchar globo", "Explotar algo", "Sonar alarma", "Sonar timbre", "Golpear puerta", "Recibir paquete", "Abrir sobre", "Leer testamento", "Ganar herencia", "Perder juicio", "Ir preso", "Salir libre", "Escapar", "Esconderse", "Asustar alguien", "Hacer broma", "Ser broma", "Caer trampa", "Mentir mal", "Decir verdad", "Contar secreto", "Escuchar chisme", "Espiar", "Ser espiado", "Ver famoso", "Pedir autógrafo", "Sacar foto", "Salir tele", "Salir diario", "Ganar concurso", "Perder apuesta", "Pagar apuesta", "Cumplir reto", "Hacer ridículo", "Tener vergüenza", "Ponerse rojo", "Sudar frío", "Temblar miedo", "Tartamudear", "Quedar mudo", "Gritar fuerte", "Salir corriendo", "Desmayarse", "Despertar sueño", "Tener pesadilla", "Ver futuro", "Viajar tiempo", "Ver ovni", "Ser abducido", "Ver monstruo", "Esconder cama", "Tapar ojos", "Tapar oídos"]
    s_l2_en = ["Opening box", "Ripping paper", "Reading letter", "Seeing msg", "Answering phone", "Opening door", "Light on", "Light off", "Closing eyes", "Making wish", "Blowing candle", "Cutting cake", "Toasting cup", "Throwing rice", "Throwing bouquet", "Catching bouquet", "Showing ring", "Kneeling down", "Saying yes", "Saying no", "Crying emotion", "Laughing nerves", "Yelling goal", "Jumping joy", "Running hug", "Kissing mouth", "Slapping face", "Throwing water", "Wetting all", "Dirtying clothes", "Breaking glass", "Falling floor", "Slipping", "Tripping", "Crashing", "Losing something", "Finding something", "Seeing ghost", "Hearing noise", "Smelling bad", "Smelling good", "Eating something", "Tasting flavor", "Burning tongue", "Biting tongue", "Popping balloon", "Exploding something", "Alarm ringing", "Doorbell ringing", "Knocking door", "Getting package", "Opening envelope", "Reading will", "Winning inheritance", "Losing trial", "Going jail", "Going free", "Escaping", "Hiding", "Scaring someone", "Pranking", "Being pranked", "Falling trap", "Lying bad", "Telling truth", "Telling secret", "Hearing gossip", "Spying", "Being spied", "Seeing celeb", "Asking autograph", "Taking photo", "Being on TV", "Being in news", "Winning contest", "Losing bet", "Paying bet", "Doing dare", "Being ridiculous", "Being ashamed", "Blushing red", "Sweating cold", "Shaking fear", "Stuttering", "Going mute", "Screaming loud", "Running away", "Fainting", "Waking up", "Having nightmare", "Seeing future", "Time travel", "Seeing UFO", "Abduction", "Seeing monster", "Hiding bed", "Covering eyes", "Covering ears"]

    while len(s_l2) < 100: s_l2.append("Sorpresa Extra L2 " + str(len(s_l2)))
    while len(s_l2_en) < 100: s_l2_en.append("Surprise Extra L2 " + str(len(s_l2_en)))
    s_l2 = s_l2[:100]; s_l2_en = s_l2_en[:100]

    for i in range(100): rows.append(["Sorpresa", "Media", s_l2[i], s_l2_en[i]])
    
    s_l3 = ["Fiesta sorpresa arruinada", "Regalo equivocado vergonzoso", "Torta cae al piso", "Piñata golpea cabeza", "Vela incendia mantel", "Anillo compromiso tragado", "Novia dice que no", "Novio huye boda", "Cura olvida nombre", "Perro orina vestido", "Gato araña torta", "Niño grita silencio", "Abuela baila reggaeton", "Tio borracho discurso", "Vomitar en regalo", "Romper regalo caro", "Ropa interior cae", "Pantalón roto agacharse", "Moco nariz foto", "Diente manchado labial", "Peluca vuela viento", "Zapato taco roto", "Caerse escenario premio", "Discurso mudo pánico", "Micrófono no anda", "Luz corta momento", "Tropezar alfombra roja", "Chocar puerta vidrio", "Saludar maniquí error", "Hablar solo espejo", "Celular suena velorio", "Reír en momento triste", "Llorar en chiste", "Estornudar en comida", "Eructar en beso", "Tirarse pedo silencio", "Roncar en cine", "Dormir en hombro ajeno", "Baba en almohada ajena", "Confundir persona saludo", "Abrazar desconocido calle", "Subir auto equivocado", "Entrar baño equivocado", "Olavier papel baño", "Agua inodoro salpica", "Quedarse encerrado ascensor", "Ascensor cae sueño", "Avión cae sueño", "Perderse en ciudad", "Robo billetera viaje", "Perder pasaporte vuelo", "Policía arresta error", "Perro muerde traste", "Pájaro caga cabeza", "Auto moja lluvia", "Paraguas vuelta viento", "Rayo cae cerca", "Trueno asusta salto", "Luz apaga ducha", "Agua fría ducha", "Jabón ojo arde", "Resbalar baño golpe", "Toalla cae frente gente", "Malla sale mar", "Ola revuelca bikini", "Cangrejo pinza dedo", "Medusa pica espalda", "Arena comida picnic", "Hormiga muerde pie", "Abeja pica nariz", "Mosquito zumba oído", "Mosca boca tragar", "Gusano manzana morder", "Leche agria beber", "Pan duro diente", "Huevo podrido olor", "Basura bolsa rompe", "Llave rompe cerradura", "Auto no arranca noche", "Goma pinchada lluvia", "Gato negro cruza", "Espejo roto 7 años", "Sal derramada mala", "Paraguas abierto adentro", "Pasar bajo escalera", "Martes 13 miedo", "Viernes 13 Jason", "Ver fantasma sábana", "Oir ruidos sótano", "Puerta abre sola", "Luz prende sola", "Sombra mueve sola", "Muñeca mira sola", "Payaso abajo cama", "Monstruo armario abre", "Susto infarto casi", "Pelo blanco susto", "Temblor piernas miedo", "Grito mudo pesadilla"]
    s_l3_en = ["Surprise party ruined", "Wrong gift shame", "Cake floor drop", "Piñata head hit", "Candle fire cloth", "Ring swallowed", "Bride says no", "Groom runs away", "Priest forgets name", "Dog pee dress", "Cat scratch cake", "Kid yells silence", "Grandma twerking", "Drunk uncle speech", "Vomit on gift", "Break expensive gift", "Underwear drop", "Pants rip squat", "Booger nose photo", "Lipstick teeth stain", "Wig wind fly", "Heel broken shoe", "Stage fall award", "Silent panic speech", "Mic dead", "Light out moment", "Trip red carpet", "Hit glass door", "Greet mannequin", "Talk mirror alone", "Phone ring funeral", "Laugh sad moment", "Cry at joke", "Sneeze on food", "Burp during kiss", "Fart silent room", "Snore in movie", "Sleep stranger shoulder", "Drool stranger pillow", "Hug stranger mistake", "Hug wrong person", "Enter wrong car", "Enter wrong WC", "Forget WC paper", "Toilet water splash", "Stuck in elevator", "Elevator fall dream", "Plane crash dream", "Lost in city", "Wallet theft trip", "Lose passport flight", "Cop arrest error", "Dog bite butt", "Bird poop head", "Car splash rain", "Umbrella flip wind", "Lightning strike near", "Thunder scare jump", "Light out shower", "Cold water shower", "Soap eye burn", "Slip bath hit", "Towel drop public", "Suit off sea", "Wave bikini fail", "Crab pinch finger", "Jellyfish sting back", "Sand picnic food", "Ant bite foot", "Bee sting nose", "Mosquito ear buzz", "Fly mouth swallow", "Worm apple bite", "Sour milk drink", "Hard bread tooth", "Rotten egg smell", "Trash bag rip", "Key break lock", "Car dead night", "Flat tire rain", "Black cat cross", "Mirror break bad", "Spilled salt bad", "Umbrella inside bad", "Walk under ladder", "Tuesday 13 fear", "Friday 13 Jason", "See ghost sheet", "Hear basement noise", "Door opens self", "Light on self", "Shadow moves self", "Doll looks self", "Clown under bed", "Monster closet open", "Scare heart attack", "White hair scare", "Shaking legs fear", "Silent scream dream"]

    while len(s_l3) < 100: s_l3.append("Sorpresa Extra " + str(len(s_l3)))
    while len(s_l3_en) < 100: s_l3_en.append("Surprise Extra L3 " + str(len(s_l3_en)))
    s_l3 = s_l3[:100]; s_l3_en = s_l3_en[:100]

    for i in range(100): rows.append(["Sorpresa", "Alta", s_l3[i], s_l3_en[i]])

    # ---------------- VERANO ----------------
    ve_l1 = ["Sol", "Playa", "Arena", "Mar", "Ola", "Piscina", "Bikini", "Malla", "Short", "Ojotas", "Lentes", "Gorra", "Sombrero", "Toalla", "Crema", "Bronceador", "Protector", "Sombrilla", "Reposera", "Balde", "Pala", "Castillo", "Caracol", "Cangrejo", "Pez", "Medusa", "Algas", "Barco", "Velero", "Lancha", "Moto", "Surf", "Windsurf", "Kitesurf", "Kayak", "Canoa", "Remo", "Salvavidas", "Flotador", "Colchoneta", "Inflable", "Pelota", "Paletas", "Tejo", "Voley", "Fútbol", "Helado", "Jugo", "Agua", "Gaseosa", "Cerveza", "Licuado", "Fruta", "Sandía", "Melón", "Ananá", "Coco", "Maíz", "Choclo", "Churros", "Facturas", "Mate", "Tereré", "Camping", "Carpa", "Fuego", "Asado", "Guitarra", "Canción", "Noche", "Estrellas", "Luna", "Mosquito", "Repelente", "Ventilador", "Aire", "Calor", "Sudar", "Ducha", "Siesta", "Vacaciones", "Viaje", "Ruta", "Auto", "Peaje", "Hotel", "Cabaña", "Amigos", "Familia", "Fiesta", "Boliche", "Baile", "Música", "Amor", "Beso", "Abrazo", "Foto", "Video", "Recuerdo"]
    ve_l1_en = ["Sun", "Beach", "Sand", "Sea", "Wave", "Pool", "Bikini", "Swimsuit", "Shorts", "Flipflops", "Glasses", "Cap", "Hat", "Towel", "Cream", "Tanner", "Protector", "Umbrella", "Chair", "Bucket", "Shovel", "Castle", "Shell", "Crab", "Fish", "Jellyfish", "Algae", "Boat", "Sailboat", "Boat", "JetSki", "Surf", "Windsurf", "Kitesurf", "Kayak", "Canoe", "Paddle", "Lifeguard", "Floatie", "Mat", "Inflatable", "Ball", "Paddles", "Tejo", "Volley", "Soccer", "Icecream", "Juice", "Water", "Soda", "Beer", "Smoothie", "Fruit", "Watermelon", "Melon", "Pineapple", "Coconut", "Corn", "Corn", "Churros", "Pastries", "Mate", "Terere", "Camping", "Tent", "Fire", "BBQ", "Guitar", "Song", "Night", "Stars", "Moon", "Mosquito", "Repellent", "Fan", "AC", "Heat", "Sweat", "Shower", "Nap", "Vacation", "Trip", "Road", "Car", "Toll", "Hotel", "Cabin", "Friends", "Family", "Party", "Club", "Dance", "Music", "Love", "Kiss", "Hug", "Photo", "Video", "Memory"]

    while len(ve_l1) < 100: ve_l1.append("Verano Extra L1 " + str(len(ve_l1)))
    while len(ve_l1_en) < 100: ve_l1_en.append("Summer Extra L1 " + str(len(ve_l1_en)))
    ve_l1 = ve_l1[:100]; ve_l1_en = ve_l1_en[:100]

    for i in range(100): rows.append(["Verano", "Baja", ve_l1[i], ve_l1_en[i]])
    
    ve_l2 = ["Tomar sol", "Nadar mar", "Saltar olas", "Hacer castillo", "Jugar paletas", "Excavar pozo", "Enterrar pies", "Juntar caracoles", "Buscar cangrejos", "Pescar orilla", "Tirar caña", "Nadar perro", "Correr playa", "Caminar orilla", "Ver atardecer", "Ver amanecer", "Sacar foto", "Poner crema", "Poner sombrilla", "Abrir reposera", "Inflar colchoneta", "Tirar frisbee", "Jugar voley", "Jugar fútbol", "Comer choclo", "Comer churros", "Tomar helado", "Beber cerveza", "Tomar mate", "Hacer asado", "Prender fuego", "Tocar guitarra", "Cantar fogón", "Contar historias", "Mirar estrellas", "Matar mosquito", "Poner repelente", "Prender aire", "Prender ventilador", "Dormir siesta", "Leer libro", "Escuchar música", "Bailar playa", "Ir fiesta", "Conocer gente", "Besar amor", "Manejar ruta", "Cargar nafta", "Pagar peaje", "Llegar hotel", "Armar carpa", "Inflar colchón", "Hacer bolso", "Lavar malla", "Secar toalla", "Sacudir arena", "Limpiar auto", "Comprar hielo", "Llenar heladera", "Cocinar fideos", "Lavar platos", "Tener calor", "Sudar mucho", "Ducharse frío", "Mojarse manguera", "Tirar agua", "Guerra agua", "Inflar globos", "Jugar carnaval", "Tirar espuma", "Mojar camiseta", "Tirarse pileta", "Hacer bomba", "Nadar bajo agua", "Aguantar respirar", "Flotar espalda", "Hacer la plancha", "Usar antiparras", "Usar patas rana", "Bucear", "Ver peces", "Sacar cangrejo", "Pisar alga", "Tocar medusa", "Gritar agua fría", "Correr arena caliente", "Quemar pies", "Buscar sombra", "Tomar sombra", "Pedir licuado", "Comer ensalada", "Hacer dieta", "Romper dieta", "Comer todo", "Engordar verano", "Adelgazar verano", "Estar bronceado", "Estar rojo", "Pelarse piel"]
    ve_l2_en = ["Sunbathing", "Sea swimming", "Wave jumping", "Castle making", "Paddle playing", "Hole digging", "Burying feet", "Shell collecting", "Crab hunting", "Shore fishing", "Rod casting", "Dog swimming", "Beach running", "Shore walking", "Sunset watching", "Sunrise watching", "Taking photo", "Cream applying", "Umbrella fix", "Chair unfolding", "Mat inflating", "Frisbee throw", "Volley playing", "Soccer playing", "Corn eating", "Churros eating", "Icecream eating", "Beer drinking", "Mate drinking", "BBQ making", "Fire lighting", "Guitar playing", "Fire singing", "Story telling", "Star gazing", "Mosquito killing", "Repellent on", "AC on", "Fan on", "Nap sleeping", "Book reading", "Music listening", "Beach dancing", "Party going", "Meeting people", "Love kissing", "Road driving", "Gas filling", "Toll paying", "Hotel arriving", "Tent pitching", "Bed inflating", "Bag packing", "Suit washing", "Towel drying", "Sand shaking", "Car cleaning", "Ice buying", "Cooler filling", "Pasta cooking", "Dish washing", "Being hot", "Sweating lot", "Cold shower", "Hose wetting", "Water throw", "Water war", "Balloon inflate", "Carnival play", "Foam spray", "T-shirt wet", "Pool jump", "Cannonball", "Underwater swim", "Holding breath", "Back float", "Floating", "Goggles use", "Fins use", "Diving", "Fish watching", "Crab catch", "Step algae", "Touch jelly", "Yell cold water", "Run hot sand", "Burn feet", "Find shade", "Sit shade", "Order smoothie", "Eat salad", "Dieting", "Breaking diet", "Eating all", "Summer fat", "Summer thin", "Being tan", "Being red", "Peeling skin"]

    while len(ve_l2) < 100: ve_l2.append("Verano Extra L2 " + str(len(ve_l2)))
    while len(ve_l2_en) < 100: ve_l2_en.append("Summer Extra L2 " + str(len(ve_l2_en)))
    ve_l2 = ve_l2[:100]; ve_l2_en = ve_l2_en[:100]

    for i in range(100): rows.append(["Verano", "Media", ve_l2[i], ve_l2_en[i]])

    ve_l3 = ["Arena en la malla", "Arena en el sandwich", "Helado derretido mano", "Gaviota roba comida", "Cangrejo muerde dedo", "Medusa pica pierna", "Alga toca pie susto", "Ola revuelca fuerte", "Perder malla ola", "Tragar agua salada", "Agua entra nariz", "Oído tapado agua", "Quemadura sol espalda", "Pelarse piel hombros", "Marca lentes sol", "Marca remera sol", "Pisar vidrio playa", "Cortarse pie roca", "Pincharse con erizo", "Perder ojota mar", "Romper ojota caminando", "Mochila llena arena", "Celular cae agua", "Lentes caen agua", "Llaves pierden arena", "Auto queda arena", "Goma pinchada ruta", "Aire auto no anda", "Ventana auto trabada", "Tráfico ruta vuelta", "Peaje fila larga", "Baño ruta sucio", "Mosquito no deja dormir", "Mosca en la sopa", "Abeja en el jugo", "Hormigas en picnic", "Carpa vuela viento", "Lluvia inunda carpa", "Colchón desinfla noche", "Vecino camping ruidoso", "Música fuerte lado", "Pelota pega cara", "Paleta pega cabeza", "Perro sacude agua", "Niño tira arena", "Castillo rompe ola", "Pozo cae alguien", "Sombrilla vuela viento", "Reposera cierra dedo", "Toalla vuela lejos", "Bronceador ojo arde", "Protector blanco cara", "Pelo verde pileta", "Cloro arde ojos", "Pileta agua sucia", "Bebé hace caca pileta", "Tobogán agua traba", "Malla engancha clavo", "Tirarse panzazo", "Saltar y caer mal", "Resbalar borde pileta", "Caer vestido pileta", "Tirar alguien pileta", "Mojar ropa seca", "Celular moja lluvia", "Ropa no seca nunca", "Olor humedad ropa", "Valija no cierra", "Olvidar algo hotel", "Perder bus vuelta", "Llegar tarde trabajo", "Extrañar la playa", "Odiar la ciudad", "Oficina calor aire roto", "Ventilador tira aire caliente", "Sudar ropa trabajo", "Mancha sudor axila", "Desodorante no anda", "Piel pica mosquito", "Rascarse picadura sangre", "Infección oído agua", "Hongos pies ducha", "Quemar asado viento", "Carbón no prende", "Carne cae tierra", "Cerveza caliente fea", "Gaseosa sin gas", "Hielo derretido todo", "Heladera no enfría", "Comida pudre calor", "Leche corta calor", "Mayonesa fea sol", "Diarrea verano", "Vómito autovia", "Mareo barco pesca", "Anzuelo engancha dedo", "Caña pesca rompe"]
    ve_l3_en = ["Sand in swimsuit", "Sand in sandwich", "Melted icecream hand", "Seagull steals food", "Crab bites finger", "Jellyfish stings leg", "Algae touch scare", "Wave tumbles hard", "Lose suit wave", "Swallow salt water", "Water up nose", "Ear clogged water", "Sunburn back red", "Peeling skin shoulders", "Sunglass tan lines", "Shirt tan lines", "Step glass beach", "Cut foot rock", "Urchin sting", "Lose flipflop sea", "Break flipflop walk", "Backpack full sand", "Phone drops water", "Glasses drop water", "Keys lost sand", "Car stuck sand", "Flat tire road", "Car AC broken", "Window stuck car", "Traffic jam return", "Toll long line", "Dirty road WC", "Mosquito no sleep", "Fly in soup", "Bee in juice", "Ants in picnic", "Tent flies wind", "Rain floods tent", "Mattress deflates", "Loud camping neighbor", "Loud music side", "Ball hits face", "Paddle hits head", "Dog shakes water", "Kid throws sand", "Castle wave break", "Hole fall person", "Umbrella fly wind", "Chair pinch finger", "Towel flies away", "Sunscreen eye burn", "White face cream", "Green hair pool", "Chlorine eye burn", "Dirty pool water", "Baby poop pool", "Slide stuck water", "Suit snag nail", "Belly flop pain", "Jump bad fall", "Slip pool edge", "Fall pool dressed", "Throw someone pool", "Wet dry clothes", "Phone wet rain", "Clothes never dry", "Damp smell clothes", "Bag wont close", "Forgot item hotel", "Miss bus return", "Late for work", "Miss the beach", "Hate the city", "Office hot AC broke", "Fan blows hot air", "Sweat work clothes", "Pit stain sweat", "Deo fails", "Itchy mosquito bite", "Scratch bite blood", "Ear infection water", "Foot fungus shower", "Burn BBQ wind", "Coal wont light", "Meat falls dirt", "Warm beer yuck", "Flat soda warm", "Ice melted all", "Cooler not cold", "Food rot heat", "Milk sour heat", "Mayo bad sun", "Summer diarrhea", "Car vomit road", "Seasick fishing", "Hook finger snag", "Rod break fish"]

    while len(ve_l3) < 100: ve_l3.append("Verano Extra L3 " + str(len(ve_l3)))
    while len(ve_l3_en) < 100: ve_l3_en.append("Summer Extra L3 " + str(len(ve_l3_en)))
    ve_l3 = ve_l3[:100]; ve_l3_en = ve_l3_en[:100]

    for i in range(100): rows.append(["Verano", "Alta", ve_l3[i], ve_l3_en[i]])

    # ---------------- JUEGOS ----------------
    j_l1 = ["Ajedrez", "Damas", "Dominó", "Cartas", "Poker", "Truco", "Uno", "Ludo", "Oca", "Monopoly", "Teg", "Estanciero", "Rompecabezas", "Puzzle", "Videojuego", "Consola", "Joystick", "Pantalla", "Mario", "Sonic", "Zelda", "Minecraft", "Fortnite", "FIFA", "PES", "Sims", "GTA", "Tetris", "Pacman", "Space", "Candy", "Clash", "Among", "Roblox", "Lol", "Dota", "CS", "Valorant", "Overwatch", "Call", "Halo", "Gears", "God", "War", "Final", "Resident", "Silent", "Street", "Mortal", "Kombat", "Tekken", "Smash", "Brawl", "Pokemon", "Digimon", "YuGiOh", "Magic", "Rol", "Dados", "Cubilete", "Generala", "Casita", "Muñecas", "Autitos", "Soldaditos", "Bloques", "Lego", "Plastilina", "Dibujo", "Pintura", "Escondidas", "Mancha", "Pilladita", "Congelados", "Estatua", "Silla", "Rayuela", "Saltar", "Soga", "Elástico", "Bolitas", "Canicas", "Trompo", "Yoyo", "Barrilete", "Cometa", "Pelota", "Fútbol", "Basquet", "Voley", "Tenis", "Golf", "Rugby", "Hockey", "Béisbol", "Softbol", "Handball"]
    j_l1_en = ["Chess", "Checkers", "Dominoes", "Cards", "Poker", "Truco", "Uno", "Ludo", "Goose", "Monopoly", "Risk", "Estanciero", "Puzzle", "Jigsaw", "Videogame", "Console", "Joystick", "Screen", "Mario", "Sonic", "Zelda", "Minecraft", "Fortnite", "FIFA", "PES", "Sims", "GTA", "Tetris", "Pacman", "Space", "Candy", "Clash", "Among", "Roblox", "LoL", "Dota", "CS", "Valorant", "Overwatch", "Call", "Halo", "Gears", "God", "War", "Final", "Resident", "Silent", "Street", "Mortal", "Kombat", "Tekken", "Smash", "Brawl", "Pokemon", "Digimon", "YuGiOh", "Magic", "RPG", "Dice", "Cup", "Yahtzee", "House", "Dolls", "Cars", "Soldiers", "Blocks", "Lego", "Playdoh", "Drawing", "Painting", "HideSeek", "Tag", "Catch", "Freeze", "Statue", "Chairs", "Hopscotch", "Jump", "Rope", "Elastic", "Marbles", "Marbles", "Top", "Yoyo", "Kite", "Kite", "Ball", "Soccer", "Basket", "Volley", "Tennis", "Golf", "Rugby", "Hockey", "Baseball", "Softball", "Handball"]

    while len(j_l1) < 100: j_l1.append("Juego Extra " + str(len(j_l1)))
    while len(j_l1_en) < 100: j_l1_en.append("Game Extra " + str(len(j_l1_en)))
    j_l1 = j_l1[:100]; j_l1_en = j_l1_en[:100]

    for i in range(100): rows.append(["Juegos", "Baja", j_l1[i], j_l1_en[i]])
    
    j_l2 = ["Mover peón", "Comer reina", "Hacer jaque", "Gritar truco", "Cantar envido", "Mezclar cartas", "Repartir cartas", "Tirar dados", "Mover ficha", "Caer carcel", "Comprar casa", "Pagar alquiler", "Armar puzzle", "Perder pieza", "Prender consola", "Cargar juego", "Guardar partida", "Pasar nivel", "Matar jefe", "Ganar vida", "Perder vida", "Game over", "Insertar moneda", "Soplar cartucho", "Apretá botón", "Romper joystick", "Gritar gol", "Festejar triunfo", "Llorar derrota", "Hacer trampa", "Ser baneado", "Tener lag", "Cortar internet", "Jugar online", "Usar chat", "Insultar noob", "Ser pro", "Hacer stream", "Ver tutorial", "Leer guía", "Comprar skin", "Abrir caja", "Ganar premio", "Subir ranking", "Bajar ranking", "Jugar equipo", "Traicionar amigo", "Hacer alianza", "Construir base", "Romper base", "Plantar bomba", "Desactivar bomba", "Rescatar rehén", "Manejar auto", "Chocar auto", "Disparar arma", "Recargar bala", "Usar poción", "Tirar hechizo", "Invocar monstruo", "Curar amigo", "Revivir amigo", "Saltar pozo", "Agarrar moneda", "Comer hongo", "Crecer grande", "Hacerse chico", "Correr rápido", "Volar avión", "Nadar agua", "Escalar muro", "Abrir cofre", "Encontrar llave", "Resolver enigma", "Abrir puerta", "Pasar final", "Sacar trofeo", "Jugar muñecas", "Peinar muñeca", "Vestir muñeca", "Chocar autitos", "Armar torre", "Tirar torre", "Amasar plastilina", "Hacer muñeco", "Pintar dibujo", "Jugar mancha", "Correr amigo", "Tocar base", "Contar hasta 10", "Buscar escondite", "Quedarse quieto", "Saltar soga", "Tirar trompo", "Remontar barrilete", "Patear pelota", "Atajar penal"]
    j_l2_en = ["Move pawn", "Take queen", "Checkmate", "Yell Truco", "Call Envido", "Shuffle cards", "Deal cards", "Roll dice", "Move piece", "Go to jail", "Buy house", "Pay rent", "Build puzzle", "Lose piece", "Console on", "Load game", "Save game", "Pass level", "Kill boss", "Gain life", "Lose life", "Game over", "Insert coin", "Blow cartridge", "Press button", "Break joystick", "Yell goal", "Celebrate win", "Cry loss", "Cheat", "Get banned", "Have lag", "Internet cut", "Play online", "Use chat", "Insult noob", "Be pro", "Stream live", "Watch tutorial", "Read guide", "Buy skin", "Open box", "Win prize", "Rank up", "Rank down", "Team play", "Betray friend", "Make alliance", "Build base", "Destroy base", "Plant bomb", "Defuse bomb", "Rescue hostage", "Drive car", "Crash car", "Shoot gun", "Reload ammo", "Use potion", "Cast spell", "Summon monster", "Heal friend", "Revive friend", "Jump pit", "Grab coin", "Eat mushroom", "Grow big", "Shrink small", "Run fast", "Fly plane", "Swim water", "Climb wall", "Open chest", "Find key", "Solve puzzle", "Open door", "Beat game", "Get trophy", "Play dolls", "Comb doll", "Dress doll", "Crash cars", "Build tower", "Knock tower", "Knead dough", "Make figure", "Paint drawing", "Play tag", "Chase friend", "Touch base", "Count to 10", "Find hiding", "Stay still", "Jump rope", "Spin top", "Fly kite", "Kick ball", "Save penalty"]

    while len(j_l2) < 100: j_l2.append("Juego Extra L2 " + str(len(j_l2)))
    while len(j_l2_en) < 100: j_l2_en.append("Game Extra L2 " + str(len(j_l2_en)))
    j_l2 = j_l2[:100]; j_l2_en = j_l2_en[:100]

    for i in range(100): rows.append(["Juegos", "Media", j_l2[i], j_l2_en[i]])
    
    j_l3 = ["Perder por lag", "Mamá apaga consola", "Hermanito borra partida", "Joystick sin batería", "Gato pisa teclado", "Internet se corta", "Juego se tilda", "Pantalla azul muerte", "Cartucho no anda", "Disco rayado error", "Soplar cartucho mil veces", "Cable corto joystick", "Tele blanco y negro", "Peces mueren Sims", "Casa quema Sims", "Pileta sin escalera Sims", "Creeper explota casa", "Caer lava diamantes", "Perder todo inventario", "No guardar partida horas", "Jefe final mata", "Quedar 1 HP", "M morir zona", "Teammate troll", "AFK en ranked", "Insultar en ruso", "Banear cuenta permanente", "Hackear cuenta robo", "Comprar skin sin querer", "Gastar plata mamá", "Tarjeta rechazada juego", "Olvidar contraseña", "Perder torneo final", "Quedar segundo lugar", "Tirar penal afuera", "Gol en contra nabo", "Romper tele control", "Romper teclado bronca", "Tirar mouse pared", "Gritar noche vecinos", "Vecino llama policía", "Dormir clase sueño", "Ojos rojos monitor", "Dedo acalambrado click", "Muñeca túnel carpiano", "Silla gamer rompe", "Auriculares solo uno", "Microfono acopla feo", "Lag 999ms", "FPS bajos 10", "Placa video quema", "PC explota humo", "Consola luces rojas", "Perder pieza puzzle alfombra", "Perro come pieza", "Carta marcada trampa", "Esconder as manga", "Falta envido mentira", "Cantar mal truco", "Mesa coja dominó", "Dados caen piso", "Perder dados sillón", "Ficha monopoly perdida", "Pelea familiar monopoly", "Tirar tablero bronca", "Robar banco monopoly", "Hacer trampa cartas", "Estatua mueve pierde", "Escondida nadie busca", "Quedar atrapado escondite", "Mancha nadie toca", "Saltar soga tropezar", "Elástico rompe pierna", "Bolita traga niño", "Trompo rompe vidrio", "Barrilete cable luz", "Pelota casa vecino", "Vecino pincha pelota", "Perro muerde pelota", "Vidrio roto pelotazo", "Golpear amigo raqueta", "Caerse patines diente", "Bici sin frenos", "Skate rompe hueso", "Raspar rodilla asfalto", "Llorar perder juego", "No saber perder", "Ser mal perdedor", "Ser mal ganador", "Burlarse perdedor", "Llorar desconsolado", "Romper amistad juego", "Juego mesa aburrido", "Instrucciones confusas"]
    j_l3_en = ["Losing due to lag", "Mom turns off console", "Brother deletes save", "Joystick battery dead", "Cat steps keyboard", "Internet cuts out", "Game freezes crash", "Blue screen death", "Cartridge fails", "Scratched disk error", "Blowing cartridge x1000", "Short cable controller", "TV black white", "Fish die Sims", "House burns Sims", "Pool no ladder Sims", "Creeper blows house", "Fall lava diamonds", "Lose all inventory", "No save hours", "Final boss kill", "Left with 1 HP", "Dying in zone", "Teammate troll", "AFK in ranked", "Insulting in Russian", "Perma ban account", "Hacked account stolen", "Accidental skin buy", "Spending moms money", "Card declined game", "Forgot password", "Lose final tourney", "Second place loss", "Miss penalty kick", "Own goal idiot", "Break TV controller", "Smash keyboard rage", "Throw mouse wall", "Yell night neighbors", "Neighbor calls cops", "Sleep class sleepy", "Red eyes monitor", "Cramped finger click", "Wrist carpel tunnel", "Gamer chair break", "Headphones one side", "Mic bad feedback", "Lag 999ms", "Low FPS 10", "GPU burns out", "PC explodes smoke", "Red ring death", "Lose puzzle piece rug", "Dog eats piece", "Marked card cheat", "Ace in sleeve", "Fake Envido lie", "Bad Truco call", "Wobbly domino table", "Dice fall floor", "Lose dice couch", "Monopoly piece lost", "Family fight Monopoly", "Flip board rage", "Steal bank Monopoly", "Cheating cards", "Statue moves loses", "Hide seek no seek", "Stuck hiding spot", "Tag no touch", "Jump rope trip", "Elastic leg snap", "Marble swallow kid", "Top breaks glass", "Kite power line", "Ball neighbors house", "Neighbor pops ball", "Dog bites ball", "Glass broken ball", "Hit friend racket", "Fall skates tooth", "Bike no brakes", "Skate bone break", "Scrape knee asphalt", "Cry losing game", "Sore loser", "Bad loser", "Bad winner", "Mocking loser", "Crying hysterical", "End friendship game", "Boring board game", "Confusing rules"]

    while len(j_l3) < 100: j_l3.append("Juego Extra L3 " + str(len(j_l3)))
    while len(j_l3_en) < 100: j_l3_en.append("Game Extra L3 " + str(len(j_l3_en)))
    j_l3 = j_l3[:100]; j_l3_en = j_l3_en[:100]

    for i in range(100): rows.append(["Juegos", "Alta", j_l3[i], j_l3_en[i]])
    
    return rows

if __name__ == "__main__":
    data = get_data()
    with open('db_part5.csv', 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f); writer.writerow(['Categoría', 'Nivel', 'Español (Latino)', 'Inglés']); writer.writerows(data)
