# -*- coding: utf-8 -*-
import csv

def get_data():
    rows = []
    
    # ---------------- PELICULAS ----------------
    pl1 = ["Titanic", "Avatar", "Shrek", "Coco", "Frozen", "Matrix", "Rocky", "Alien", "Joker", "Barbie", "Thor", "Batman", "Superman", "Spiderman", "Ironman", "Hulk", "Cars", "Up", "Nemo", "Dumbo", "Bambi", "Tarzan", "Mulan", "Moana", "Encanto", "Luca", "Soul", "Rio", "Bolt", "Sonic", "Mario", "Minions", "Gru", "Sing", "Trolls", "Pets", "Lego", "Wonka", "Dune", "Elvis", "Top Gun", "Jaws", "It", "Saw", "Scream", "Creed", "Glass", "Split", "Signs", "Click", "Ted", "Mask", "Hook", "Elf", "Big", "Splash", "Ghost", "Speed", "Heat", "Seven", "Troy", "300", "Brave", "Wall-E", "Ratatouille", "Bolt", "Turbo", "Plane", "Home", "Epic", "Rango", "Hop", "Lorax", "Croods", "Boss", "Ferdinand", "Storks", "Smallfoot", "Abominable", "Scoob", "Spirit", "Ron", "Bad Guys", "Wish", "Elemental", "Turning Red", "Lightyear", "Strange World", "Raya", "Onward", "Incredibles", "Monsters Inc", "Toy Story", "Lion King", "Aladdin", "Pinocchio", "Cinderella"]
    pl1_en = ["Titanic", "Avatar", "Shrek", "Coco", "Frozen", "Matrix", "Rocky", "Alien", "Joker", "Barbie", "Thor", "Batman", "Superman", "Spiderman", "Ironman", "Hulk", "Cars", "Up", "Nemo", "Dumbo", "Bambi", "Tarzan", "Mulan", "Moana", "Encanto", "Luca", "Soul", "Rio", "Bolt", "Sonic", "Mario", "Minions", "Despicable Me", "Sing", "Trolls", "Pets", "Lego Movie", "Wonka", "Dune", "Elvis", "Top Gun", "Jaws", "It", "Saw", "Scream", "Creed", "Glass", "Split", "Signs", "Click", "Ted", "Mask", "Hook", "Elf", "Big", "Splash", "Ghost", "Speed", "Heat", "Seven", "Troy", "300", "Brave", "Wall-E", "Ratatouille", "Bolt", "Turbo", "Plane", "Home", "Epic", "Rango", "Hop", "Lorax", "Croods", "Boss Baby", "Ferdinand", "Storks", "Smallfoot", "Abominable", "Scoob", "Spirit", "Ron Gone Wrong", "Bad Guys", "Wish", "Elemental", "Turning Red", "Lightyear", "Strange World", "Raya", "Onward", "Incredibles", "Monsters Inc", "Toy Story", "Lion King", "Aladdin", "Pinocchio", "Cinderella"]
    
    print(f"Peliculas Baja: ES={len(pl1)}, EN={len(pl1_en)}")
    # Pad or trim to 100
    while len(pl1) < 100: pl1.append("Extra Peli " + str(len(pl1)))
    while len(pl1_en) < 100: pl1_en.append("Extra Movie " + str(len(pl1_en)))
    pl1 = pl1[:100]; pl1_en = pl1_en[:100]

    for i in range(100): rows.append(["Peliculas", "Baja", pl1[i], pl1_en[i]])

    pl2 = ["Harry Potter", "Star Wars", "Jurassic Park", "El Padrino", "Forrest Gump", "Rey León", "Toy Story", "Buscando a Nemo", "Indiana Jones", "Volver al Futuro", "Señor Anillos", "Piratas Caribe", "Hombres de Negro", "Los Vengadores", "Rápido y Furioso", "Misión Imposible", "Sexto Sentido", "Pulp Fiction", "Gladiador", "Corazón Valiente", "Naufrago", "Rescatando Soldado Ryan", "La Vida es Bella", "Cinema Paradiso", "Amelie", "El Resplandor", "Psicosis", "El Exorcista", "La Momia", "King Kong", "Godzilla", "Terminator", "Depredador", "Robocop", "Duro de Matar", "Arma Mortal", "Loca Academia", "Mi Pobre Angelito", "Cazafantasmas", "Gremlins", "E.T.", "Goonies", "Beetlejuice", "Familia Addams", "Casper", "Jumanji", "Space Jam", "Matilda", "Juego Gemelas", "Stuart Little", "Dr. Dolittle", "Mentiroso Mentiroso", "Todopoderoso", "Ace Ventura", "Tonto y Retonto", "Loco por Mary", "Legalmente Rubia", "Chicas Pesadas", "Diario Princesa", "Un Viernes Locos", "Juego de Espías", "Mini Espías", "Sharkboy Lavagirl", "Escuela de Rock", "Niñera a Prueba", "Más Barato Docena", "Papá por Siempre", "Mira quien Habla", "Tres Hombres y Biberón", "Querida Encogí Niños", "Beethoven", "Liberen a Willy", "Flipper", "Babe", "101 Dálmatas", "La Dama y Vagabundo", "Aristogatos", "Libro de la Selva", "Robin Hood", "Espada en la Piedra", "Alicia en Maravillas", "Peter Pan", "Bella Durmiente", "Blancanieves", "Sirenita", "Bella y Bestia", "Pocahontas", "Jorobado Notre Dame", "Hércules", "Mulán", "Atlantis", "Planeta Tesoro", "Lilo and Stitch", "Tierra de Osos", "Vacas Vaqueras", "Chicken Little", "Salvaje", "Bolt un perro"]
    pl2_en = ["Harry Potter", "Star Wars", "Jurassic Park", "Godfather", "Forrest Gump", "Lion King", "Toy Story", "Finding Nemo", "Indiana Jones", "Back to Future", "Lord Rings", "Pirates Caribbean", "Men in Black", "Avengers", "Fast & Furious", "Mission Impossible", "Sixth Sense", "Pulp Fiction", "Gladiator", "Braveheart", "Cast Away", "Saving Private Ryan", "Life is Beautiful", "Cinema Paradiso", "Amelie", "The Shining", "Psycho", "Exorcist", "The Mummy", "King Kong", "Godzilla", "Terminator", "Predator", "Robocop", "Die Hard", "Lethal Weapon", "Police Academy", "Home Alone", "Ghostbusters", "Gremlins", "E.T.", "Goonies", "Beetlejuice", "Addams Family", "Casper", "Jumanji", "Space Jam", "Matilda", "Parent Trap", "Stuart Little", "Dr. Dolittle", "Liar Liar", "Bruce Almighty", "Ace Ventura", "Dumb and Dumber", "Something About Mary", "Legally Blonde", "Mean Girls", "Princess Diaries", "Freaky Friday", "Spy Game", "Spy Kids", "Sharkboy Lavagirl", "School of Rock", "Pacifier", "Cheaper Dozen", "Mrs. Doubtfire", "Look Who Talking", "3 Men and Baby", "Honey Shrunk Kids", "Beethoven", "Free Willy", "Flipper", "Babe", "101 Dalmatians", "Lady and Tramp", "Aristocats", "Jungle Book", "Robin Hood", "Sword in Stone", "Alice in Wonderland", "Peter Pan", "Sleeping Beauty", "Snow White", "Little Mermaid", "Beauty and Beast", "Pocahontas", "Hunchback Notre Dame", "Hercules", "Mulan", "Atlantis", "Treasure Planet", "Lilo and Stitch", "Brother Bear", "Home on Range", "Chicken Little", "The Wild", "Bolt"]
    
    print(f"Peliculas Media: ES={len(pl2)}, EN={len(pl2_en)}")
    while len(pl2) < 100: pl2.append("Peli Extra " + str(len(pl2)))
    while len(pl2_en) < 100: pl2_en.append("Movie Extra " + str(len(pl2_en)))
    pl2 = pl2[:100]; pl2_en = pl2_en[:100]

    for i in range(100): rows.append(["Peliculas", "Media", pl2[i], pl2_en[i]])
    
    pl3 = ["Jack el destripador bailando", "Frankenstein cosiendo medias", "Dracula con ajo", "Hombre lobo afeitándose", "Momia desenredada", "Fantasma atrapado sábana", "Bruja sin escoba", "Zombi vegetariano", "Vampiro donando sangre", "Alien perdido mapa", "Godzilla pisando lego", "King Kong cayendo", "Terminator oxidado", "Robocop sin batería", "Predator visible", "Gremlin mojado", "ET llamando equivocado", "Jumanji dados perdidos", "Harry Potter sin varita", "Voldemort con nariz", "Gandalf cortando barba", "Frodo perdiendo anillo", "Gollum regalando anillo", "Yoda hablando normal", "Darth Vader con asma", "Luke soy tu sobrino", "Han Solo dispara segundo", "Chewbacca afeitado", "R2D2 sin aceite", "C3PO oxidado", "Indiana Jones miedo araña", "Marty McFly llegando tarde", "Doc Brown sin plutonio", "Jack Sparrow sin ron", "Capitán Garfio aplaudiendo", "Peter Pan creciendo", "Campanita sin polvo", "Aladdin frotando mal", "Genio atrapado lámpara", "Jasmine cayendo alfombra", "Simba maullando", "Mufasa cayendo colchón", "Scar siendo bueno", "Timon sin Pumba", "Pocahontas sin viento", "Mulán maquillándose mal", "Hércules debilucho", "Tarzan cayendo liana", "Jane gritando ratón", "Bella amando Gastón", "Bestia afeitándose", "Ariel ahogándose", "Cenicienta zapato grande", "Blancanieves manzana rica", "Pinocho nariz quieta", "Dumbo orejas chicas", "Bambi pisando fuerte", "101 Dálmatas sin manchas", "Cruella amando perros", "Buzz Lightyear cayendo estilo", "Woody sin sombrero", "Jessie sin trenza", "Sr. Papa sin piezas", "Rex sin brazos", "Slinky enredado", "Hamm sin monedas", "Barbie despeinada", "Ken sin ropa", "Shrek guapo", "Fiona humana", "Burro mudo", "Gato Botas sin botas", "Dragona escupe agua", "Kung Fu Panda flaco", "Manny Mamut pelado", "Diego Tigre sin dientes", "Sid Perezoso rápido", "Scrat agarra nuez", "Rayo McQueen pinchado", "Mate oxidado mal", "Nemo nadando bien", "Dory memoria elefante", "Sully asustado", "Mike Wazowski dos ojos", "Boo asustando", "Wall-E limpio", "Eva oxidada", "Remy cocinando mal", "Lingüini chef experto", "Carl Fredricksen joven", "Russell sin medallas", "Dug ardilla ignora", "Ralph Rompe nada", "Vanellope maneja lento", "Elsa fuego", "Anna hielo", "Olaf derretido", "Moana miedo agua", "Maui sin anzuelo"]
    pl3_en = ["Jack Ripper dancing", "Frankenstein sewing socks", "Dracula garlic allergy", "Werewolf shaving", "Mummy unraveled", "Ghost sheet trapped", "Witch no broom", "Vegetarian Zombie", "Vampire blood donor", "Alien lost map", "Godzilla stepping lego", "King Kong falling", "Rusty Terminator", "Robocop low battery", "Predator visible", "Wet Gremlin", "ET wrong number", "Jumanji lost dice", "Potter no wand", "Voldemort with nose", "Gandalf beard trim", "Frodo losing ring", "Gollum giving ring", "Yoda normal talk", "Vader asthma attack", "Luke im your nephew", "Han Solo shoots 2nd", "Shaved Chewbacca", "R2D2 needs oil", "Rusty C3PO", "Indy fear spider", "Marty Late McFly", "Doc Brown no plutonium", "Jack Sparrow no rum", "Hook clapping", "Peter Pan growing", "Tinkerbell no dust", "Aladdin rub fail", "Genie lamp stuck", "Jasmine carpet fall", "Simba meowing", "Mufasa mattress fall", "Scar being nice", "Timon no Pumbaa", "Pocahontas no wind", "Mulan bad makeup", "Weak Hercules", "Tarzan vine fall", "Jane mouse scream", "Belle loving Gaston", "Beast shaving", "Ariel drowning", "Cinderella big shoe", "Snow White tasty apple", "Pinocchio nose still", "Dumbo small ears", "Bambi stomping", "Dalmatians no spots", "Cruella loving dogs", "Buzz falling style", "Woody lost hat", "Jessie no braid", "Mr Potato parts lost", "Rex no arms", "Slinky tangled", "Hamm no coins", "Messy Barbie", "Naked Ken", "Handsome Shrek", "Human Fiona", "Mute Donkey", "Puss no boots", "Dragon water spit", "Skinny Panda", "Bald Manny", "Diego toothless", "Fast Sid", "Scrat catches nut", "McQueen flat tire", "Mater bad rust", "Nemo swimming fine", "Dory elephant memory", "Sully scared", "Mike two eyes", "Boo scaring", "Clean Wall-E", "Rusty Eva", "Remy bad cook", "Linguini chef pro", "Young Carl", "Russell no badges", "Dug ignoring squirrel", "Ralph breaks nothing", "Vanellope slow driver", "Elsa fire power", "Anna ice power", "Olaf melted", "Moana fear water", "Maui lost hook"]
    
    print(f"Peliculas Alta: ES={len(pl3)}, EN={len(pl3_en)}")
    while len(pl3) < 100: pl3.append("Extra Peli " + str(len(pl3)))
    while len(pl3_en) < 100: pl3_en.append("Extra Movie " + str(len(pl3_en)))
    pl3 = pl3[:100]; pl3_en = pl3_en[:100]

    for i in range(100): rows.append(["Peliculas", "Alta", pl3[i], pl3_en[i]])

    # ---------------- HEROES ----------------
    h_l1 = ["Batman", "Superman", "Spiderman", "Ironman", "Hulk", "Thor", "Capitán América", "Mujer Maravilla", "Flash", "Aquaman", "Pantera Negra", "Viuda Negra", "Ojo de Halcón", "Doctor Strange", "Antman", "Wolverine", "Deadpool", "Cíclope", "Tormenta", "Magneto", "Profesor X", "Bestia", "Gambito", "Rogue", "Jean Grey", "Mystique", "Daredevil", "Punisher", "Elektra", "Blade", "Hellboy", "Spawn", "Linterna Verde", "Flecha Verde", "Superichica", "Batichica", "Robin", "Cyborg", "Raven", "Starfire", "Chico Bestia", "Shazam", "Black Adam", "Joker", "Harley Quinn", "Pingüino", "Acertijo", "Dos Caras", "Gatúbela", "Bane", "Espantapájaros", "Hiedra Venenosa", "Mr. Freeze", "Lex Luthor", "Zod", "Doomsday", "Darkseid", "Thanos", "Loki", "Ultron", "Venom", "Carnage", "Duende Verde", "Dr. Octopus", "Electro", "Sandman", "Mysterio", "Buitre", "Kingpin", "Bullseye", "Red Skull", "Hydra", "Soldado Invierno", "Falcon", "War Machine", "Visión", "Bruja Escarlata", "Quicksand", "Groot", "Rocket", "Star Lord", "Gamora", "Drax", "Mantis", "Nebula", "Yondu", "Valkiria", "Hela", "Surtur", "Dormammu", "Mandarín", "Shang Chi", "Eternals", "Ikaris", "Sersi", "Thena", "Gilgamesh", "Kingo", "Sprite"]
    h_l1_en = ["Batman", "Superman", "Spiderman", "Ironman", "Hulk", "Thor", "Captain America", "Wonder Woman", "Flash", "Aquaman", "Black Panther", "Black Widow", "Hawkeye", "Doctor Strange", "Antman", "Wolverine", "Deadpool", "Cyclops", "Storm", "Magneto", "Professor X", "Beast", "Gambit", "Rogue", "Jean Grey", "Mystique", "Daredevil", "Punisher", "Elektra", "Blade", "Hellboy", "Spawn", "Green Lantern", "Green Arrow", "Supergirl", "Batgirl", "Robin", "Cyborg", "Raven", "Starfire", "Beast Boy", "Shazam", "Black Adam", "Joker", "Harley Quinn", "Penguin", "Riddler", "Two Face", "Catwoman", "Bane", "Scarecrow", "Poison Ivy", "Mr. Freeze", "Lex Luthor", "Zod", "Doomsday", "Darkseid", "Thanos", "Loki", "Ultron", "Venom", "Carnage", "Green Goblin", "Dr. Octopus", "Electro", "Sandman", "Mysterio", "Vulture", "Kingpin", "Bullseye", "Red Skull", "Hydra", "Winter Soldier", "Falcon", "War Machine", "Vision", "Scarlet Witch", "Quicksilver", "Groot", "Rocket", "Star Lord", "Gamora", "Drax", "Mantis", "Nebula", "Yondu", "Valkyrie", "Hela", "Surtur", "Dormammu", "Mandarin", "Shang Chi", "Eternals", "Ikaris", "Sersi", "Thena", "Gilgamesh", "Kingo", "Sprite"]

    print(f"Heroes Baja: ES={len(h_l1)}, EN={len(h_l1_en)}")
    while len(h_l1) < 100: h_l1.append("Extra Hero " + str(len(h_l1)))
    while len(h_l1_en) < 100: h_l1_en.append("Extra Hero " + str(len(h_l1_en)))
    h_l1 = h_l1[:100]; h_l1_en = h_l1_en[:100]

    for i in range(100): rows.append(["Heroes", "Baja", h_l1[i], h_l1_en[i]])
    
    h_l2 = ["Tirar telaraña", "Volar alto", "Rayos ojos", "Fuerza bruta", "Correr rápido", "Nadar profundo", "Escalar pared", "Lanzar escudo", "Martillo trueno", "Lazo verdad", "Garras adamantium", "Curación rápida", "Telepatía mental", "Mover metal", "Controlar clima", "Teletransportar", "Hacerse invisible", "Hacerse gigante", "Hacerse pequeño", "Estirar cuerpo", "Prender fuego", "Congelar todo", "Convertir piedra", "Flecha explosiva", "Batarang lanzar", "Batimóvil manejar", "Capa ondear", "Antifaz poner", "Traje romper", "Grito sónico", "Mordida vampiro", "Veneno inyectar", "Gas miedo", "Risa loca", "Moneda tirar", "Paraguas arma", "Gato negro", "Planta carnívora", "Hielo disparar", "Anillo poder", "Linterna luz", "Flecha verde", "Volar avión invisible", "Romper cadenas", "Levantar auto", "Parar tren", "Salvar gato", "Atrapar ladrón", "Pelear villano", "Esquivar balas", "Saltar edificio", "Caer de pie", "Caminar techo", "Balancear red", "Trepar torre", "Romper pared", "Abrir caja fuerte", "Hackear compu", "Usar gadget", "Curar herida", "Vendar brazo", "Entrenar lucha", "Meditar templo", "Leer mente", "Borrar memoria", "Hablar peces", "Respirar agua", "Controlar fuego", "Controlar hielo", "Controlar tierra", "Controlar aire", "Controlar electricidad", "Controlar magnetismo", "Viajar tiempo", "Ver futuro", "Cambiar forma", "Imitar voz", "Clonar cuerpo", "Regenerar brazo", "Resistir bala", "Romper espada", "Usar armadura", "Cargar energía", "Disparar rayo", "Lanzar misil", "Explotar bomba", "Salvar mundo", "Vengar muerte", "Proteger ciudad", "Esconder identidad", "Usar máscara", "Quitar máscara", "Revelar cara", "Ser millonario", "Ser pobre", "Ser huérfano", "Tener mayordomo", "Vivir cueva", "Vivir castillo", "Vivir base secreta"]
    h_l2_en = ["Shooting web", "Flying high", "Eye beams", "Brute strength", "Running fast", "Swimming deep", "Wall climbing", "Shield throw", "Thunder hammer", "Lasso truth", "Adamantium claws", "Fast healing", "Mental telepathy", "Moving metal", "Weather control", "Teleporting", "Invisibility", "Gaining size", "Shrinking", "Body stretch", "Flame on", "Freezing all", "Stone turn", "Explosive arrow", "Batarang throw", "Batmobile drive", "Cape waver", "Mask put on", "Suit rip", "Sonic scream", "Vampire bite", "Venom inject", "Fear gas", "Crazy laugh", "Coin flip", "Umbrella gun", "Black cat", "Carnivorous plant", "Ice shoot", "Power ring", "Lantern light", "Green arrow", "Invisible jet fly", "Breaking chains", "Lifting car", "Stopping train", "Saving cat", "Catching thief", "Fighting villain", "Dodging bullets", "Building jump", "Landing feet", "Ceiling walk", "Web swing", "Tower climb", "Wall break", "Safe crack", "Pc hack", "Gadget use", "Wound heal", "Arm bandage", "Fight train", "Temple meditate", "Mind read", "Memory wipe", "Fish talk", "Water breathe", "Fire control", "Ice control", "Earth control", "Air control", "Electric control", "Magnet control", "Time travel", "Future see", "Shape shift", "Voice mimic", "Body clone", "Arm regen", "Bullet resist", "Sword break", "Armor use", "Energy charge", "Beam shoot", "Missile launch", "Bomb explode", "World save", "Death avenge", "City protect", "Identity hide", "Mask wear", "Mask remove", "Face reveal", "Being rich", "Being poor", "Being orphan", "Having butler", "Cave living", "Castle living", "Secret base live"]
    
    print(f"Heroes Media: ES={len(h_l2)}, EN={len(h_l2_en)}")
    while len(h_l2) < 100: h_l2.append("Extra Hero Skill " + str(len(h_l2)))
    while len(h_l2_en) < 100: h_l2_en.append("Extra Hero Skill " + str(len(h_l2_en)))
    h_l2 = h_l2[:100]; h_l2_en = h_l2_en[:100]

    for i in range(100): rows.append(["Heroes", "Media", h_l2[i], h_l2_en[i]])
    
    h_l3 = ["Batman sin bati-cinturón", "Superman miedo altura", "Spiderman sin red", "Ironman traje oxidado", "Hulk calambre pierna", "Thor pierde martillo", "Capitán escudo roto", "Mujer Maravilla pelo enredado", "Flash atado cordones", "Aquaman ahogado piscina", "Pantera alergia gatos", "Viuda negra araña miedo", "Ojo Halcón sin lentes", "Dr Strange truco falla", "Antman pisado zapato", "Wolverine corta pan", "Deadpool sin chistes", "Cíclope lentes rotos", "Tormenta paraguas viento", "Magneto pegado heladera", "Prof X rueda pinchada", "Bestia depilada", "Gambito pierde cartas", "Rogue toca sin querer", "Jean Grey dolor cabeza", "Mystique piel azul destiñe", "Daredevil choca pared", "Punisher pistola agua", "Linterna Verde sin pilas", "Flecha Verde arco roto", "Supergirl capa enganchada", "Robin calzones rotos", "Cyborg virus windows", "Raven dolor panza", "Starfire pelo quemado", "Chico Bestia pulga", "Shazam olvida palabra", "Joker chiste malo", "Harley mazo goma", "Pingüino resbala hielo", "Acertijo olvida respuesta", "Dos Caras moneda cae", "Gatúbela bola pelos", "Bane asma fuerte", "Espantapájaros miedo cuervo", "Hiedra alergia polen", "Freeze derrite calor", "Lex peluca vuela", "Zod cuello torcido", "Thanos chasquido falla", "Loki mentira descubierta", "Ultron sin wifi", "Venom diente picado", "Duende patineta rota", "Octopus brazos nudo", "Electro corto circuito", "Sandman hecho barro", "Mysterio casco empañado", "Buitre alas rotas", "Kingpin dieta estricta", "Soldado Invierno brazo óxido", "Falcon pluma alergia", "Vision gema apagada", "Wanda magia explota", "Quicksilver cansa rápido", "Groot astilla dedo", "Rocket cola pisada", "Star Lord baile feo", "Gamora piel verde mancha", "Drax invisible nadie cree", "Mantis antena rota", "Nebula pieza suelta", "Yondu silbido desafinado", "Valquiria caballo cae", "Hela casco engancha", "Surtur fósforo mojado", "Shang Chi patada aire", "Eternals olvidados todos", "Hulk pantalón no rompe", "Thor gordo cerveza", "Capitan América viejo", "Ironman batería baja", "Spiderman traje sucio", "Batman tarjeta rechazada", "Superman kriptonita bolsillo", "Aquaman habla sushi", "Flash llega tarde", "Mujer Maravilla lazo nudo", "Linterna Verde daltónico", "Daredevil bastón perdido", "Antman hormiga pisa", "Wasp matamoscas golpe", "Thing piedra riñón", "Torch fuego apaga", "Invisible Woman ropa flota", "Reed Richards nudo cuerpo", "Silver Surfer tabla rompe", "Galactus hambre dieta"]
    h_l3_en = ["Batman no belt", "Superman fear heights", "Spiderman no web", "Ironman rusty suit", "Hulk leg cramp", "Thor lost hammer", "Cap broken shield", "Wonder Woman tangled hair", "Flash tied laces", "Aquaman drowning pool", "Panther cat allergy", "Widow spider fear", "Hawkeye lost glasses", "Strange trick fail", "Antman stepped on", "Wolverine cutting bread", "Deadpool no jokes", "Cyclops broken glasses", "Storm umbrella flip", "Magneto stuck fridge", "Prof X flat tire", "Shaved Beast", "Gambit lost cards", "Rogue touch accident", "Jean Grey headache", "Mystique blue fade", "Daredevil wall hit", "Punisher water gun", "Lantern no battery", "Green Arrow bow snap", "Supergirl cape snag", "Robin ripped briefs", "Cyborg windows virus", "Raven tummy ache", "Starfire burnt hair", "Beast Boy flea", "Shazam forgot word", "Joker bad joke", "Harley rubber mallet", "Penguin ice slip", "Riddler forgot answer", "Two Face coin drop", "Catwoman hairball", "Bane asthma attack", "Scarecrow crow fear", "Ivy pollen allergy", "Freeze melting heat", "Lex wig fly", "Zod stiff neck", "Thanos snap fail", "Loki lie caught", "Ultron no wifi", "Venom cavity tooth", "Goblin broken board", "Octopus arms knot", "Electro short circuit", "Sandman mud pie", "Mysterio foggy helm", "Vulture broken wing", "Kingpin strict diet", "Winter Soldier rusty arm", "Falcon feather allergy", "Vision gem off", "Wanda magic boom", "Quicksilver tired fast", "Groot finger splinter", "Rocket tail step", "Star Lord bad dance", "Gamora skin stain", "Drax invisible fail", "Mantis broken antenna", "Nebula loose part", "Yondu bad whistle", "Valkyrie horse trip", "Hela helm snag", "Surtur wet match", "Shang Chi air kick", "Eternals forgotten", "Hulk pants stay on", "Thor fat beer", "Old Captain America", "Ironman low battery", "Spiderman dirty suit", "Batman card declined", "Superman kryptonite pocket", "Aquaman talks sushi", "Flash late arrival", "Wonder Woman knot lasso", "Colorblind Green Lantern", "Daredevil lost cane", "Antman ant step", "Wasp swatter hit", "Thing kidney stone", "Torch fire out", "Invisible clothes floating", "Reed Richards body knot", "Surfer board break", "Galactus diet hunger"]
    
    print(f"Heroes Alta: ES={len(h_l3)}, EN={len(h_l3_en)}")
    while len(h_l3) < 100: h_l3.append("Extra Hero Funny " + str(len(h_l3)))
    while len(h_l3_en) < 100: h_l3_en.append("Extra Hero Funny " + str(len(h_l3_en)))
    h_l3 = h_l3[:100]; h_l3_en = h_l3_en[:100]

    for i in range(100): rows.append(["Heroes", "Alta", h_l3[i], h_l3_en[i]])
    
    return rows

if __name__ == "__main__":
    data = get_data()
    with open('db_part2.csv', 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f); writer.writerow(['Categoría', 'Nivel', 'Español (Latino)', 'Inglés']); writer.writerows(data)
