# -*- coding: utf-8 -*-
import csv

def get_data():
    rows = []
    
    # ---------------- ACCION ----------------
    l1 = ["Correr", "Saltar", "Bailar", "Cantar", "Comer", "Dormir", "Llorar", "Reír", "Nadar", "Volar", "Escribir", "Leer", "Cocinar", "Pintar", "Barrer", "Manejar", "Pescar", "Aplaudir", "Abrazar", "Besar", "Estirar", "Gatear", "Tropezar", "Resbalar", "Caer", "Levantar", "Empujar", "Tirar", "Abrir", "Cerrar", "Doblar", "Romper", "Pegar", "Cortar", "Lijar", "Fregar", "Sacudir", "Planchar", "Coser", "Tejer", "Borda", "Hornear", "Freír", "Hervir", "Picar", "Rallar", "Batir", "Amasar", "Mezclar", "Servir", "Beber", "Morder", "Masticar", "Tragar", "Escupir", "Soplar", "Silbar", "Gritar", "Susurrar", "Hablar", "Escuchar", "Oler", "Tocar", "Mirar", "Observar", "Guiñar", "Parpadear", "Sonreír", "Bostezar", "Estornudar", "Tosér", "Roncar", "Soñar", "Despertar", "Estudiar", "Pensar", "Recordar", "Olvidar", "Imaginar", "Crear", "Destruir", "Construir", "Martillar", "Atornillar", "Serruchar", "Cavar", "Plantar", "Regar", "Cosechar", "Podar", "Trepar", "Escalar", "Saltar", "Girar", "Rodar", "Caminar", "Marchar", "Correr", "Trotar"]
    l1_en = ["Run", "Jump", "Dance", "Sing", "Eat", "Sleep", "Cry", "Laugh", "Swim", "Fly", "Write", "Read", "Cook", "Paint", "Sweep", "Drive", "Fish", "Clap", "Hug", "Kiss", "Stretch", "Crawl", "Trip", "Slip", "Fall", "Lift", "Push", "Pull", "Open", "Close", "Fold", "Break", "Glue", "Cut", "Sand", "Scrub", "Shake", "Iron", "Sew", "Knit", "Embroider", "Bake", "Fry", "Boil", "Chop", "Grate", "Whisk", "Knead", "Mix", "Serve", "Drink", "Bite", "Chew", "Swallow", "Spit", "Blow", "Whistle", "Scream", "Whisper", "Talk", "Listen", "Smell", "Touch", "Look", "Observe", "Wink", "Blink", "Smile", "Yawn", "Sneeze", "Cough", "Snore", "Dream", "Wake", "Study", "Think", "Remember", "Forget", "Imagine", "Create", "Destroy", "Build", "Hammer", "Screw", "Saw", "Dig", "Plant", "Water", "Harvest", "Prune", "Climb", "Scale", "Jump", "Spin", "Roll", "Walk", "March", "Run", "Jog"]
    
    # Check length
    while len(l1) < 100: l1.append("Accion Extra L1 " + str(len(l1)))
    while len(l1_en) < 100: l1_en.append("Action Extra L1 " + str(len(l1_en)))
    l1 = l1[:100]; l1_en = l1_en[:100]

    for i in range(100): rows.append(["Accion", "Baja", l1[i], l1_en[i]])

    l2 = ["Planchar camisa", "Atar cordones", "Lavarse dientes", "Cortar pasto", "Inflar globo", "Cambiar pañal", "Palar nieve", "Martillar clavo", "Exprimir naranja", "Abrir frasco", "Manejar auto", "Andar bici", "Pagar cuenta", "Pedir taxi", "Hacer cama", "Lavar platos", "Secar pelo", "Maquillarse cara", "Afeitarse barba", "Cortarse uñas", "Bañar perro", "Dar comida", "Sacar basura", "Regar plantas", "Barrer piso", "Trapear suelo", "Limpiar vidrios", "Sacudir polvo", "Ordenar cuarto", "Doblar ropa", "Colgar cuadro", "Cambiar foco", "Arreglar enchufe", "Pintar pared", "Lijar madera", "Cortar leña", "Prender fuego", "Apagar vela", "Soplar torta", "Abrir regalo", "Envolver caja", "Escribir carta", "Leer diario", "Mandar mensaje", "Hablar celular", "Sacar selfi", "Grabar video", "Buscar llaves", "Perder billetera", "Encontrar moneda", "Contar dinero", "Pagar tarjeta", "Firmar papel", "Sellar sobre", "Pegar estampilla", "Tirar beso", "Dar abrazo", "Chocar manos", "Saludar mano", "Despedirse lejos", "Hacer dedo", "Parar bondi", "Subir escalera", "Bajar ascensor", "Abrir paraguas", "Cerrar campera", "Atar bufanda", "Ponerse gorro", "Sacarse botas", "Colgar abrigo", "Hacer té", "Calentar agua", "Servir café", "Batir crema", "Untar manteca", "Cortar pan", "Pelar papa", "Hervir fideos", "Colar arroz", "Freír huevo", "Saltear verdura", "Condimentar", "Probar sopa", "Salar comida", "Soplar caliente", "Masticar chicle", "Hacer globo", "Sonarse nariz", "Limpiar lentes", "Ponerse lentes", "Sacar foto", "Posar foto", "Sonreír cámara", "Saludar cámara", "Aplaudir show", "Silbar canción", "Tararear ritmo", "Chasquear dedos"]
    l2_en = ["Ironing shirt", "Tying shoelaces", "Brushing teeth", "Mowing lawn", "Inflating balloon", "Changing diaper", "Shoveling snow", "Hammering nail", "Squeezing orange", "Opening jar", "Driving car", "Riding bike", "Paying bill", "Hailing taxi", "Making bed", "Washing dishes", "Drying hair", "Applying makeup", "Shaving beard", "Cutting nails", "Bathing dog", "Feeding pet", "Taking trash", "Watering plants", "Sweeping floor", "Mopping floor", "Cleaning windows", "Dusting furniture", "Tidying room", "Folding clothes", "Hanging picture", "Changing bulb", "Fixing plug", "Painting wall", "Sanding wood", "Chopping wood", "Lighting fire", "Blowing candle", "Blowing cake", "Opening gift", "Wrapping box", "Writing letter", "Reading news", "Texting msg", "Talking phone", "Taking selfie", "Recording video", "Finding keys", "Losing wallet", "Finding coin", "Counting money", "Paying card", "Signing paper", "Sealing envelope", "Sticking stamp", "Blowing kiss", "Giving hug", "High five", "Shaking hands", "Waving goodbye", "Hitchhiking", "Stopping bus", "Climbing stairs", "Taking elevator", "Opening umbrella", "Zipping jacket", "Tying scarf", "Putting hat", "Taking boots", "Hanging coat", "Making tea", "Boiling water", "Pouring coffee", "Whipping cream", "Spreading butter", "Slicing bread", "Peeling potato", "Boiling pasta", "Straining rice", "Frying egg", "Sautéing veg", "Seasoning food", "Tasting soup", "Salting food", "Blowing hot", "Chewing gum", "Blowing bubble", "Blowing nose", "Cleaning glasses", "Wearing glasses", "Taking photo", "Posing photo", "Smiling camera", "Waving camera", "Clapping show", "Whistling song", "Humming tune", "Snapping fingers"]
    
    while len(l2) < 100: l2.append("Accion Extra L2 " + str(len(l2)))
    while len(l2_en) < 100: l2_en.append("Action Extra L2 " + str(len(l2_en)))
    l2 = l2[:100]; l2_en = l2_en[:100]

    for i in range(100): rows.append(["Accion", "Media", l2[i], l2_en[i]])

    l3 = ["Caminar sobre carbón", "Estornudar sin poder", "Pisar caca perro", "Caminar contra viento", "Matar mosca molesta", "Ponerse jeans ajustados", "Quemar comida esconderla", "Bailar tango escoba", "Desactivar bomba miedo", "Equilibrio cuerda floja", "Saltar en paracaídas", "Nadar con cocodrilos", "Escalar Everest ojotas", "Correr maratón muletas", "Boxear con sombra", "Pelear con almohada", "Hacer malabares huevos", "Tragar espada falsa", "Domar silla salvaje", "Montar toro mecánico", "Surfear tsunami", "Esquiar sin nieve", "Patinar sobre aceite", "Trepar edificio vidiros", "Saltar charco gigante", "Caerse en público", "Tropezar con aire", "Chocarse puerta vidrio", "Resbalar cáscara banana", "Quedarse pegado chicle", "Perderse en laberinto", "Buscar aguja pajar", "Intentar lamer codo", "Besarse a sí mismo", "Abrazar aire solo", "Pelear con mosquito", "Huir de abejas", "Sacarse muela solo", "Cortarse pelo solo", "Tatuarse a sí mismo", "Operar a corazón abierto", "Manejar ojos vendados", "Aterrizar avión emergencia", "Robar banco silencio", "Escapar de prisión", "Esconderse de policía", "Mentir en juicio", "Llorar cebolla picada", "Reírse en funeral", "Dormirse en reunión", "Roncar muy fuerte", "Babear almohada", "Caerse de la cama", "Sonámbulo caminando techo", "Tener pesadilla fea", "Despertar tarde examen", "Olvidar pantalones casa", "Romper jarrón caro", "Manchar camisa vino", "Quemar camisa plancha", "Coser botón dedo", "Martillarse el dedo", "Cortarse papel lengua", "Pincharse con cactus", "Comer ají picante", "Tragar cubo hielo", "Morder lengua fuerte", "Ahogarse con agua", "Quemar lengua café", "Congelar cerebro helado", "Estornudar fideos nariz", "Reírse bebida nariz", "Vomitar en montaña rusa", "Marearse en calesita", "Perder equilibrio barco", "Caerse bici quieta", "Chocar auto estacionado", "Rayar auto llave", "Perder llaves alcantarilla", "Tirar celular inodoro", "Romper pantalla celular", "Mojar libro prestado", "Perder boleto ganador", "Ganar y no cobrar", "Saludar persona equivocada", "Chocar los cinco aire", "Caerse silla rompiendo", "Sentarse sobre pastel", "Recibir tortazo cara", "Resbalar en ducha", "Quedarse sin papel baño", "Taparse oído agua", "Sacarse agua oído", "Rascarse espalda pared", "Intentar alcanzar espalda", "Hacer yoga y trabarse", "Desmayarse de amor", "Gritar gol equipo rival", "Cantar desafinado ducha", "Bailar sin música"]
    l3_en = ["Walking hot coals", "Failed sneeze", "Stepping dog poop", "Wind walking", "Killing nuisance fly", "Tight jeans pants", "Burning hiding food", "Tango with broom", "Defusing bomb fear", "Tightrope balance", "Skydiving jump", "Swimming crocs", "Everest flipflops", "Marathon crutches", "Shadow boxing", "Pillow fighting", "Egg juggling", "Fake sword swallow", "Taming wild chair", "Mech bull riding", "Surfing tsunami", "Skiing no snow", "Skating on oil", "Climbing glass bldg", "Jumping huge puddle", "Public fall", "Tripping on air", "Hitting glass door", "Banana slip", "Stuck in gum", "Lost in maze", "Needle in haystack", "Licking elbow", "Kissing self", "Hugging air", "Mosquito fight", "Fleeing bees", "Self tooth pull", "Self haircut", "Self tattoo", "Open heart surgery", "Blindfold driving", "Emergency landing", "Silent bank rob", "Prison escape", "Hiding from cops", "Lying in court", "Onion crying", "Funeral laughing", "Meeting sleeping", "Loud snoring", "Pillow drooling", "Bed falling", "Roof slipwalking", "Bad nightmare", "Late for exam", "Forget pants", "Breaking expensive vase", "Wine stain shirt", "Iron burn shirt", "Sewing finger", "Hammering finger", "Paper cut tongue", "Cactus prick", "Eating hot chili", "Swallowing ice cube", "Biting tongue hard", "Choking water", "Burning tongue coffee", "Brain freeze", "Sneezing noodles", "Laughing drink nose", "Rollercoaster vomit", "Carousel dizzy", "Boat losing balance", "Falling stationary bike", "Hitting parked car", "Keying car", "Keys sewer drop", "Phone toilet drop", "Breaking phone screen", "Wetting borrowed book", "Losing win ticket", "Winning collecting nil", "Waving wrong person", "Missed high five", "Breaking chair sit", "Sitting on cake", "Pie in face", "Shower slip", "Out of toilet paper", "Water stuck ear", "Shaking water ear", "Scratching back wall", "Reaching back itch", "Yoga stuck pose", "Fainting love", "Yelling wrong goal", "Singing offkey shower", "Dancing no music"]

    while len(l3) < 100: l3.append("Accion Extra L3 " + str(len(l3)))
    while len(l3_en) < 100: l3_en.append("Action Extra L3 " + str(len(l3_en)))
    l3 = l3[:100]; l3_en = l3_en[:100]

    for i in range(100): rows.append(["Accion", "Alta", l3[i], l3_en[i]])

    # ---------------- DEPORTES ----------------
    d_l1 = ["Fútbol", "Básquet", "Tenis", "Natación", "Boxeo", "Rugby", "Golf", "Vóley", "Béisbol", "Hockey", "Esquí", "Surf", "Ciclismo", "Patinaje", "Karate", "Gimnasia", "Pesca", "Atletismo", "Sumo", "Arquería", "Judo", "Taekwondo", "Lucha", "Kung Fu", "Esgrima", "Remo", "Canotaje", "Vela", "Buceo", "Waterpolo", "Handball", "Badminton", "Ping Pong", "Squash", "Padel", "Cricket", "Polo", "Equitación", "Rodeo", "Automovilismo", "Motociclismo", "Rally", "Karting", "Formula 1", "Skate", "Snowboard", "Paracaidismo", "Alpinismo", "Escalada", "Senderismo", "Triatlón", "Maratón", "Decatlón", "Salto Alto", "Salto Largo", "Garrocha", "Lanzamiento", "Bala", "Jabalina", "Disco", "Martillo", "Carrera", "Relevos", "Vallas", "Marcha", "Crossfit", "Yoga", "Pilates", "Zumba", "Aeróbica", "Pesas", "Culturismo", "Halvedrofilia", "Powerlifting", "Strongman", "Bolos", "Dardos", "Billar", "Pool", "Tejo", "Bocha", "Croquet", "Petanca", "Curling", "Lacrosse", "Softbol", "Netball", "Korfball", "Sepak Takraw", "Kabaddi", "Capoeira", "Parkour", "Freerunning", "Breakdance", "Cheerleading", "Acrobacia", "Malabarismo", "Trapecio", "Cuerda Floja", "Cama Elástica"]
    d_l1_en = ["Soccer", "Basketball", "Tennis", "Swimming", "Boxing", "Rugby", "Golf", "Volleyball", "Baseball", "Hockey", "Skiing", "Surfing", "Cycling", "Skating", "Karate", "Gymnastics", "Fishing", "Athletics", "Sumo", "Archery", "Judo", "Taekwondo", "Wrestling", "Kung Fu", "Fencing", "Rowing", "Canoeing", "Sailing", "Diving", "Waterpolo", "Handball", "Badminton", "Ping Pong", "Squash", "Padel", "Cricket", "Polo", "Riding", "Rodeo", "Racing", "Motorcycling", "Rally", "Karting", "Formula 1", "Skate", "Snowboard", "Skydiving", "Alpinism", "Climbing", "Hiking", "Triathlon", "Marathon", "Decathlon", "High Jump", "Long Jump", "Pole Vault", "Throw", "Shot Put", "Javelin", "Discus", "Hammer", "Race", "Relay", "Hurdles", "Walk", "Crossfit", "Yoga", "Pilates", "Zumba", "Aerobics", "Weights", "Bodybuilding", "Weightlifting", "Powerlifting", "Strongman", "Bowling", "Darts", "Billiards", "Pool", "Shuffleboard", "Bocce", "Croquet", "Petanque", "Curling", "Lacrosse", "Softball", "Netball", "Korfball", "Sepak Takraw", "Kabaddi", "Capoeira", "Parkour", "Freerunning", "Breakdance", "Cheerleading", "Acrobatics", "Juggling", "Trapeze", "Tightrope", "Trampoline"]

    while len(d_l1) < 100: d_l1.append("Deporte Extra L1 " + str(len(d_l1)))
    while len(d_l1_en) < 100: d_l1_en.append("Sport Extra L1 " + str(len(d_l1_en)))
    d_l1 = d_l1[:100]; d_l1_en = d_l1_en[:100]

    for i in range(100): rows.append(["Deportes", "Baja", d_l1[i], d_l1_en[i]])

    d_l2 = ["Meter gol", "Hacer home run", "Nocaut boxeo", "Saque tenis", "Tirar penal", "Caerse esquiando", "Atrapar pelota", "Hacer pesas", "Remar kayak", "Escalar montaña", "Andar skate", "Patinar hielo", "Hacer surf", "Nadar pecho", "Nadar espalda", "Tirar al aro", "Hacer un pase", "Atajar gol", "Sacar tarjeta roja", "Cobrar falta", "Tirar corner", "Hacer lateral", "Pedir tiempo", "Celebrar gol", "Cambiar jugador", "Lesionarse pierna", "Vendarse mano", "Ponerse casco", "Atar botines", "Inflar pelota", "Romper raqueta", "Perder pelota", "Hacer hoyo uno", "Salir del bunker", "Tirar bowling", "Hacer chuza", "Tirar dardos", "Jugar al pool", "Meter la 8", "Saltar la soga", "Hacer flexiones", "Hacer abdominales", "Correr cinta", "Pedalear bici", "Cambiar rueda", "Poner cadena", "Ajustar asiento", "Usar inflador", "Tomar agua", "Secarse sudor", "Tirar toalla", "Subir podio", "Ganar medalla", "Cantar himno", "Llorar derrota", "Abrazar equipo", "Levantar copa", "Firmar camiseta", "Dar entrevista", "Sacar foto fan", "Hacer autógrafo", "Elongar músculos", "Calentar cuerpo", "Trotar suave", "Picar pelota", "Girar pelota dedo", "Hacer jueguitos", "Cabecear pelota", "Parar de pecho", "Tirar caño", "Hacer rabona", "Tirar chilena", "Atajar penal", "Errar penal", "Pegar en palo", "Pinchar pelota", "Romper red", "Saltar valla", "Lanzar jabalina", "Tirar disco", "Saltar garrocha", "Caer colchoneta", "Nadar mariposa", "Nadar crol", "Largada carrera", "Cruzar meta", "Romper cinta", "Cronometrar tiempo", "Hacer record", "Ganar carrera", "Perder carrera", "Empatar juego", "Ir a alargue", "Definir penales", "Muerte súbita", "Hacer tacle", "Scrum rugby", "Try rugby", "Conversion rugby"]
    d_l2_en = ["Scoring goal", "Home run hit", "Boxing knockout", "Tennis serve", "Penalty shot", "Skiing fall", "Catching ball", "Lifting weights", "Kayaking", "Climbing mt", "Skateboarding", "Ice skating", "Surfing wave", "Breaststroke", "Backstroke", "Shooting hoop", "Making pass", "Saving goal", "Red card", "Calling foul", "Corner kick", "Throw in", "Timeout call", "Goal celebration", "Sub player", "Leg injury", "Wrapping hand", "Wearing helmet", "Tying cleats", "Inflating ball", "Breaking racket", "Losing ball", "Hole in one", "Sand bunker", "Bowling throw", "Strike bowl", "Throwing darts", "Playing pool", "Sinking 8ball", "Jumping rope", "Pushups", "Situps", "Treadmill run", "Pedaling bike", "Changing tire", "Fixing chain", "Adjusting seat", "Using pump", "Drinking water", "Drying sweat", "Towel throw", "Podium climb", "Winning medal", "Singing anthem", "Crying loss", "Hugging team", "Lifting cup", "Signing shirt", "Interviewing", "Fan photo", "Signing autograph", "Stretching muscles", "Warming up", "Jogging soft", "Bouncing ball", "Spinning finger", "Juggling ball", "Heading ball", "Chest stop", "Nutmeg trick", "Rabona kick", "Bicycle kick", "Saving penalty", "Missing penalty", "Hitting post", "Popping ball", "Breaking net", "Jumping hurdle", "Throwing javelin", "Throwing discus", "Pole vaulting", "Mat landing", "Butterfly swim", "Crawl swim", "Race start", "Crossing finish", "Breaking tape", "Timing race", "Record break", "Winning race", "Losing race", "Tie game", "Overtime", "Penalty shootout", "Sudden death", "Tackle rugby", "Rugby scrum", "Rugby try", "Rugby conversion"]

    while len(d_l2) < 100: d_l2.append("Deporte Extra L2 " + str(len(d_l2)))
    while len(d_l2_en) < 100: d_l2_en.append("Sport Extra L2 " + str(len(d_l2_en)))
    d_l2 = d_l2[:100]; d_l2_en = d_l2_en[:100]

    for i in range(100): rows.append(["Deportes", "Media", d_l2[i], d_l2_en[i]])
    
    d_l3 = ["Sumo bailando ballet", "Tenista rompiendo raqueta", "Arquero miedo pelota", "Surfista tiburón", "Boxeador auto nocaut", "Golfista festejo temprano", "Ciclista sin cadena", "Nadador calambre", "Basquetbolista bajo", "Esquiador árbol", "Futbolista actuando falta", "Arbitro ciego", "Mascota equipo bailando", "Jugador perdiendo shorts", "Pelota deshinflada aire", "Perro entra cancha", "Gol en contra final", "DT gritando afónico", "Hincha dormido tribuna", "Vendedor comida cancha", "Aguatero tropezando", "Camilla cayendo jugador", "Medico corriendo lento", "Periodista pelotazo", "Cámara rompiéndose", "Arco cayéndose", "Red agujereada", "Pasto muy alto", "Lluvia inunda cancha", "Nieve tapa líneas", "Viento lleva pelota", "Sol ciega arquero", "Reflectores apagados", "Riego prende partido", "Pájaro caga jugador", "Gato negro cruza", "Topo pozo cancha", "Pelota pincha clavo", "Zapato vuela aire", "Camiseta rota tirón", "Pantalón cae penal", "Medias bajas", "Cordones desatados gol", "Espinillera cae", "Venda suelta", "Pelo tapa ojos", "Sudor entra ojos", "Agua botella vuelca", "Toalla mojada cara", "Trofeo cae pie", "Medalla rompe diente", "Podio se rompe", "Himno disco rayado", "Bandera al revés", "Antorcha se apaga", "Fuego quema pelo", "Mascota ataca jugador", "Fan invade cancha", "Policía corre fan", "Perro muerde pelota", "Pelota queda techo", "Arquero hace gol", "Defensa ataja mano", "Delantero erra solo", "Pelota pega palo x3", "Gol anulado VAR", "Festejo gol offside", "Jugador choca palo", "Camilla choca carrito", "Carrito rompe motor", "Riego moja DT", "DT rompe pizarra", "Jugador ríe himno", "Jugador llora antes", "Miedo escénico penal", "Vómito cancha", "Diente volando golpe", "Sangre nariz pelotazo", "Ojo morado golpe", "Dedo doblado voley", "Calambre dos piernas", "Fatiga corre lento", "Desmayo meta maratón", "Vomito llegada carrera", "Caída bici dominó", "Rueda pinchada final", "Cadena rota subida", "Freno roto bajada", "Pez muerde nadador", "Malla rompe largada", "Antiparras llenan agua", "Gorro sale nadando", "Pared pileta dura", "Trampolín rompe salto", "Agua pileta verde", "Cloro arde ojos", "Malla se cae salto", "Juez puntaje cero"]
    d_l3_en = ["Sumo balcony dance", "Tennis racket smash", "Goalie ball fear", "Surfer shark chase", "Boxer self KO", "Golfer early celeb", "Cyclist lost chain", "Swimmer leg cramp", "Short basketballer", "Skier hitting tree", "Soccer dive acting", "Blind referee", "Mascot dancing bad", "Player losing shorts", "Ball deflating air", "Dog on field", "Own goal final", "Coach yelling lost voice", "Fan sleeping stands", "Food vendor field", "Waterboy tripping", "Stretcher dropping player", "Medic running slow", "Reporter ball hit", "Camera breaking", "Goal post falling", "Net with hole", "Grass too high", "Rain flood field", "Snow covering lines", "Wind moving ball", "Sun blinding goalie", "Lights going out", "Sprinklers mid game", "Bird poop player", "Black cat crossing", "Mole hole field", "Ball popping nail", "Shoe flying air", "Shirt ripped pull", "Pants down penalty", "Socks down", "Laces untied goal", "Shin guard falling", "Bandage loose", "Hair covering eyes", "Sweat in eyes", "Water bottle spill", "Wet towel face", "Trophy drop foot", "Medal tooth chip", "Podium breaking", "Anthem skipped record", "Flag upside down", "Torch going out", "Fire burning hair", "Mascot attack player", "Fan invading pitch", "Cop chasing fan", "Dog biting ball", "Ball stuck roof", "Goalie scoring goal", "Defender hand save", "Striker miss open", "Ball pos x3 hit", "Goal VAR cancel", "Offside celebration", "Player post hit", "Stretcher cart crash", "Cart motor break", "Sprinkler soaking coach", "Coach breaking board", "Player laughing anthem", "Player crying start", "Stage fright penalty", "Vomit field", "Tooth flying hit", "Nosebleed ball hit", "Black eye punch", "Finger bent volley", "Cramp both legs", "Fatigue slow run", "Faint finish line", "Vomit finish race", "Bike crash domino", "Flat tire finish", "Chain break hill", "Brake fail downhill", "Fish bite swimmer", "Suit rip start", "Goggles water fill", "Cap swimming away", "Pool wall hard", "Board break dive", "Pool water green", "Chlorine burn eyes", "Suit falling dive", "Judge score zero"]

    while len(d_l3) < 100: d_l3.append("Deporte Extra L3 " + str(len(d_l3)))
    while len(d_l3_en) < 100: d_l3_en.append("Sport Extra L3 " + str(len(d_l3_en)))
    d_l3 = d_l3[:100]; d_l3_en = d_l3_en[:100]

    for i in range(100): rows.append(["Deportes", "Alta", d_l3[i], d_l3_en[i]])

    # ---------------- MUSICA ----------------
    m_l1 = ["Guitarra", "Piano", "Batería", "Violín", "Trompeta", "Microfono", "Saxofón", "Flauta", "Acordeón", "Arpa", "Cantante", "DJ", "Director", "Rock", "Pop", "Jazz", "Tango", "Salsa", "Ópera", "Rap", "Reggae", "Metal", "Punk", "Disco", "Funk", "Blues", "Soul", "Folk", "Country", "Bachata", "Cumbia", "Merengue", "Reggaeton", "Trap", "Hip Hop", "Electro", "Techno", "House", "Trance", "Dubstep", "Clásica", "Barroco", "Coral", "Gospel", "Samba", "Bossa Nova", "Mariachi", "Ranchera", "Flamenco", "K-Pop", "J-Pop", "Indie", "Grunge", "Ska", "R&B", "Bolero", "Balada", "Trova", "Zarzuela", "Vals", "Polka", "Marcha", "Himno", "Canción", "Melodía", "Ritmo", "Nota", "Acorde", "Escala", "Pentagrama", "Clave", "Sol", "Fa", "Do", "Re", "Mi", "La", "Si", "Silencio", "Compás", "Tempo", "Metrónomo", "Diapasón", "Batuta", "Atril", "Partitura", "Letra", "Verso", "Coro", "Estribillo", "Puente", "Intro", "Outro", "Solo", "Dúo", "Trío", "Cuarteto", "Quinteto", "Banda", "Orquesta", "Coro"]
    m_l1_en = ["Guitar", "Piano", "Drums", "Violin", "Trumpet", "Microphone", "Saxophone", "Flute", "Accordion", "Harp", "Singer", "DJ", "Conductor", "Rock", "Pop", "Jazz", "Tango", "Salsa", "Opera", "Rap", "Reggae", "Metal", "Punk", "Disco", "Funk", "Blues", "Soul", "Folk", "Country", "Bachata", "Cumbia", "Merengue", "Reggaeton", "Trap", "Hip Hop", "Electro", "Techno", "House", "Trance", "Dubstep", "Classical", "Baroque", "Choral", "Gospel", "Samba", "Bossa Nova", "Mariachi", "Ranchera", "Flamenco", "K-Pop", "J-Pop", "Indie", "Grunge", "Ska", "R&B", "Bolero", "Ballad", "Trova", "Zarzuela", "Waltz", "Polka", "March", "Anthem", "Song", "Melody", "Rhythm", "Note", "Chord", "Scale", "Staff", "Clef", "G", "F", "C", "D", "E", "A", "B", "Silence", "Bar", "Tempo", "Metronome", "Tuning Fork", "Baton", "Stand", "Sheet Music", "Lyrics", "Verse", "Chorus", "Refrain", "Bridge", "Intro", "Outro", "Solo", "Duo", "Trio", "Quartet", "Quintet", "Band", "Orchestra", "Choir"]

    while len(m_l1) < 100: m_l1.append("Musica Extra L1 " + str(len(m_l1)))
    while len(m_l1_en) < 100: m_l1_en.append("Music Extra L1 " + str(len(m_l1_en)))
    m_l1 = m_l1[:100]; m_l1_en = m_l1_en[:100]

    for i in range(100): rows.append(["Musica", "Baja", m_l1[i], m_l1_en[i]])
    
    m_l2 = ["Tocar guitarra", "Cantar ópera", "Dirigir orquesta", "Romper guitarra", "Bailar reggaeton", "Tocar piano", "Hacer beatbox", "Afinar violín", "Tocar batería", "Cantar ducha", "Escribir canción", "Grabar disco", "Dar concierto", "Firmar autógrafo", "Subir escenario", "Bajar volumen", "Subir volumen", "Poner auriculares", "Bailar lento", "Cantar karaoke", "Tocar timbre", "Silbar canción", "Tararear", "Chasquear dedos", "Aplaudir ritmo", "Zapatear", "Tocar palmas", "Hacer pogo", "Mover cabeza", "Saltar público", "Tocar flauta", "Soplar trompeta", "Rasguear cuerdas", "Golpear tambor", "Sacudir maracas", "Tocar teclado", "Usar pedal", "Microfonear", "Ecualizar", "Mezclar música", "Hacer scratch", "Cambiar disco", "Poner vinilo", "Rebobinar cinta", "Saltar canción", "Repetir tema", "Buscar letra", "Leer partitura", "Marcar tempo", "Usar batuta", "Cantar coros", "Hacer segunda voz", "Desafinar", "Romper cuerda", "Perder púa", "Caerse escenario", "Olvidar letra", "Cantar gallo", "Gritar gol", "Quedarse afónico", "Tocar mal", "Sonar fuerte", "Sonar despacio", "Hacer silencio", "Esperar turno", "Entrar tarde", "Salir tempo", "Errar nota", "Romper baqueta", "Pinchar parche", "Acoplar mic", "Cortar cable", "Quemar amplificador", "Saltar plomos", "Probar sonido", "Chequear línea", "Afinar voz", "Calentar garganta", "Tomar agua", "Saludar público", "Pedir otra", "Tirar beso", "Agarrar regalo", "Esquivar botella", "Firmar disco", "Sacar foto", "Dar entrevista", "Hacer gira", "Viajar bus", "Dormir hotel", "Cargar equipo", "Armar escenario", "Desarmar todo", "Cobrar show", "Pagar sala", "Comprar instrum", "Vender entrada", "Cortar ticket"]
    m_l2_en = ["Playing guitar", "Singing opera", "Conducting orchestra", "Smashing guitar", "Dancing reggaeton", "Playing piano", "Beatboxing", "Tuning violin", "Playing drums", "Shower singing", "Writing song", "Recording album", "Giving concert", "Signing autograph", "Stage dive", "Volume down", "Volume up", "Headphones on", "Slow dance", "Karaoke singing", "Ringing bell", "Whistling song", "Humming", "Snapping fingers", "Clapping beat", "Tap dancing", "Clapping hands", "Moshing", "Headbanging", "Crowd surfing", "Playing flute", "Blowing trumpet", "Strumming", "Hitting drum", "Shaking maracas", "Playing keyboard", "Using pedal", "Mic check", "EQing", "Mixing music", "Scratching DJ", "Changing record", "Playing vinyl", "Rewinding tape", "Skipping song", "Repeating track", "Searching lyrics", "Reading sheet", "Marking tempo", "Using baton", "Backing vocals", "Harmony singing", "Singing offkey", "Breaking string", "Losing pick", "Falling off stage", "Forgetting lyrics", "Voice cracking", "Yelling goal", "Losing voice", "Playing bad", "Sounding loud", "Sounding soft", "Making silence", "Waiting turn", "Late entry", "Off tempo", "Wrong note", "Breaking stick", "Drumhead break", "Mic feedback", "Cutting cable", "Amp burnout", "Fuse blowing", "Sound check", "Line check", "Tuning voice", "Warming throat", "Drinking water", "Waving crowd", "Encore call", "Throwing kiss", "Catching gift", "Dodging bottle", "Signing album", "Taking photo", "Interviewing", "Touring", "Bus travel", "Hotel sleep", "Loading gear", "Stage setup", "Teardown", "Getting paid", "Paying rent", "Buying gear", "Selling ticket", "Tearing ticket"]

    while len(m_l2) < 100: m_l2.append("Musica Extra L2 " + str(len(m_l2)))
    while len(m_l2_en) < 100: m_l2_en.append("Music Extra L2 " + str(len(m_l2_en)))
    m_l2 = m_l2[:100]; m_l2_en = m_l2_en[:100]

    for i in range(100): rows.append(["Musica", "Media", m_l2[i], m_l2_en[i]])

    m_l3 = ["Rockero rompiendo guitarra llorando", "Director espantando moscas", "Cantante olvidando letra", "DJ durmiendo", "Piano con pies", "Violinista con picazón", "Baterista perdiendo palillos", "Opera rompiendo copas", "Rapero tartamudo", "Vals con esqueleto", "Guitarrista sin cuerdas", "Cantante tragando mosca", "Microfono con calambre", "Baterista rompiendo parche", "Pianista dedos atados", "Saxofonista sin aire", "Trompetista cara roja", "Flautista encantando serpientes", "Arpista dedos pegados", "Acordeonista atrapado fuelle", "DJ rayando disco abuelo", "Director perdiendo batuta", "Coro cantando mudo", "Tenor rompiendo ventanas", "Soprano rompiendo lentes", "Bajista volumen cero", "Rockstar tropezando cable", "Popstar peluca volando", "Jazzista tocando dormido", "Metalero pelo enredado", "Punk rompiendo todo menos guitarra", "Disco bailando resbaloso", "Funk olor feo", "Blues llorando verdad", "Soul gritando dolor", "Folk perdiendo banjo", "Country perdiendo sombrero", "Bachata cintura trabada", "Cumbia paso equivocado", "Merengue mareado", "Reggaeton perreo suelo", "Trap sin autotune", "Hip Hop rimando naranja", "Electro robot oxidado", "Techno disco rayado", "House casa cayendo", "Trance durmiendo parado", "Dubstep convulsionando", "Clásica director loco", "Barroco peluca cayendo", "Gospel desmayado fe", "Samba tropiezo pluma", "Mariachi sombrero tapando ojos", "Flamenco taco roto", "Kpop baile descoordinado", "Indie ropa rota", "Grunge sucio real", "Ska saltando techo", "R&B llorando lluvia", "Bolero durmiendo pareja", "Balada moco colgando", "Trova guitarra desafinada", "Zarzuela gallo terrible", "Vals pisando vestido", "Polka mareo vueltas", "Marcha soldado cayendo", "Himno letra mal", "Canción cuna despertando", "Melodía pegajosa molesta", "Ritmo cardíaco rápido", "Nota alta rompe vidrio", "Acorde disonante dolor", "Escala infinita", "Pentagrama líneas chuecas", "Clave sol dibujada mal", "Metrónomo muy rápido", "Diapasón golpeando cabeza", "Batuta volando ojo", "Atril cayendo pie", "Partitura volando viento", "Letra ilegible", "Verso olvidado", "Coro desafinado", "Estribillo repetido mil veces", "Puente roto canción", "Intro eterna", "Outro nunca termina", "Solo guitarra 20 minutos", "Dúo peleando vivo", "Trío uno falta", "Cuarteto desafinado", "Quinteto sin instrumentos", "Banda separándose vivo", "Orquesta tocando mal", "Coro tosiendo todos"]
    m_l3_en = ["Rocker smashing guitar crying", "Conductor swatting flies", "Singer forgetting lyrics", "DJ falling asleep", "Piano with feet", "Violinist itchy", "Drummer losing sticks", "Opera breaking glass", "Rapper stuttering", "Waltz with skeleton", "Guitarist no strings", "Singer swallowing fly", "Mic shock", "Drum head break", "Pianist tied fingers", "Saxophonist no air", "Trumpet red face", "Flute charming snake", "Harp sticky fingers", "Accordion trap", "DJ scratching grandpa vinyl", "Director losing baton", "Choir singing mute", "Tenor breaking windows", "Soprano breaking glasses", "Bassist zero volume", "Rockstar tripping cable", "Popstar wig fly", "Jazz playing sleep", "Metal hair tangle", "Punk breaking all but guitar", "Disco slip dance", "Funk bad smell", "Blues crying real", "Soul screaming pain", "Folk losing banjo", "Country losing hat", "Bachata waist locked", "Cumbia wrong step", "Merengue dizzy", "Reggaeton floor grind", "Trap no autotune", "HipHop orange rhyme", "Electro rusty robot", "Techno broken record", "House house falling", "Trance sleep standing", "Dubstep seizure dance", "Classical crazy conductor", "Baroque wig falling", "Gospel faint faith", "Samba feather trip", "Mariachi hat blind", "Flamenco broken heel", "Kpop bad sync", "Indie torn clothes", "Grunge real dirty", "Ska roof jump", "RnB rain cry", "Bolero sleep partner", "Ballad snot drip", "Trova out of tune", "Zarzuela bad crack", "Waltz stepping dress", "Polka dizzy spin", "March soldier fall", "Anthem wrong lyrics", "Lullaby waking up", "Melody stuck annoyance", "Rhythm heart fast", "High note break glass", "Chord dissonance pain", "Scale infinite", "Staff crooked lines", "Clef bad draw", "Metronome too fast", "Tuning fork head hit", "Baton eye hit", "Stand foot drop", "Sheet music wind fly", "Lyrics unreadable", "Verse forgotten", "Chorus off key", "Refrain repeat 1000", "Bridge broken song", "Intro eternal", "Outro never ends", "Solo guitar 20 min", "Duo fighting live", "Trio missing one", "Quartet out of tune", "Quintet no instruments", "Band breaking up live", "Orchestra playing bad", "Choir coughing all"]

    while len(m_l3) < 100: m_l3.append("Musica Extra L3 " + str(len(m_l3)))
    while len(m_l3_en) < 100: m_l3_en.append("Music Extra L3 " + str(len(m_l3_en)))
    m_l3 = m_l3[:100]; m_l3_en = m_l3_en[:100]

    for i in range(100): rows.append(["Musica", "Alta", m_l3[i], m_l3_en[i]])

    return rows

if __name__ == "__main__":
    data = get_data()
    with open('db_part3.csv', 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f); writer.writerow(['Categoría', 'Nivel', 'Español (Latino)', 'Inglés']); writer.writerows(data)
