# -*- coding: utf-8 -*-
import csv

def get_data():
    rows = []
    
    # ---------------- PROFESIONES ----------------
    l1 = ["Doctor", "Maestro", "Policía", "Bombero", "Cocinero", "Mecánico", "Pintor", "Payaso", "Mago", "Astronauta", "Juez", "Dentista", "Granjero", "Actor", "Cantante", "Soldado", "Enfermera", "Arquitecto", "Fotógrafo", "Carpintero", "Fiscal", "Notario", "Albañil", "Plomero", "Gasista", "Fletero", "Taxista", "Chofer", "Piloto", "Azafata", "Capitán", "Marinero", "Buzo", "Minero", "Leñador", "Herrero", "Sastre", "Modista", "Modelo", "Mimo", "Acróbata", "Atleta", "Coach", "Árbitro", "Caddy", "Cura", "Monja", "Pastor", "Rabino", "Imán", "Filósofo", "Escritor", "Poeta", "Periodista", "Locutor", "Editor", "Director", "Productor", "Guionista", "Camarógrafo", "Sonidista", "Iluminador", "Vestuarista", "Maquillador", "Peluquero", "Barbero", "Masajista", "Kinesiólogo", "Psicólogo", "Psiquiatra", "Cirujano", "Pediatra", "Ginecólogo", "Oculista", "Cardiólogo", "Dermatólogo", "Nutricionista", "Farmacéutico", "Bioquímico", "Científico", "Biólogo", "Químico", "Físico", "Matemático", "Astrónomo", "Historiador", "Geógrafo", "Arqueólogo", "Antropólogo", "Sociólogo", "Abogado", "Contador", "Administrador", "Economista", "Banquero", "Cajero", "Vendedor", "Gerente", "Dueño", "Presidente"]
    l1_en = ["Doctor", "Teacher", "Police", "Firefighter", "Chef", "Mechanic", "Painter", "Clown", "Magician", "Astronaut", "Judge", "Dentist", "Farmer", "Actor", "Singer", "Soldier", "Nurse", "Architect", "Photographer", "Carpenter", "Prosecutor", "Notary", "Mason", "Plumber", "Gasfitter", "Mover", "Taxi driver", "Chauffeur", "Pilot", "Stewardess", "Captain", "Sailor", "Diver", "Miner", "Lumberjack", "Blacksmith", "Tailor", "Dressmaker", "Model", "Mime", "Acrobat", "Athlete", "Coach", "Referee", "Caddy", "Priest", "Nun", "Pastor", "Rabbi", "Imam", "Philosopher", "Writer", "Poet", "Journalist", "Announcer", "Editor", "Director", "Producer", "Screenwriter", "Cameraman", "Soundman", "Lighter", "Costume", "Makeup", "Hairdresser", "Barber", "Masseur", "Kinesiologist", "Psychologist", "Psychiatrist", "Surgeon", "Pediatrician", "Gynecologist", "Oculist", "Cardiologist", "Dermatologist", "Nutritionist", "Pharmacist", "Biochemist", "Scientist", "Biologist", "Chemist", "Physicist", "Mathematician", "Astronomer", "Historian", "Geographer", "Archaeologist", "Anthropologist", "Sociologist", "Lawyer", "Accountant", "Manager", "Economist", "Banker", "Teller", "Salesman", "Manager", "Owner", "President"]
    
    while len(l1) < 100: l1.append("Profesion Extra " + str(len(l1)))
    while len(l1_en) < 100: l1_en.append("Job Extra " + str(len(l1_en)))
    l1 = l1[:100]; l1_en = l1_en[:100]

    for i in range(100): rows.append(["Profesiones", "Baja", l1[i], l1_en[i]])

    l2 = ["Apagar incendio", "Operar paciente", "Dirigir tráfico", "Sacar muela", "Enseñar mate", "Cocinar sopa", "Arreglar auto", "Ordeñar vaca", "Sacar foto", "Construir pared", "Escribir multa", "Enseñar leer", "Pintar cuadro", "Servir café", "Contar dinero", "Arreglar tubería", "Sembrar semillas", "Cortar leña", "Hacer vestido", "Maquillar novia", "Tomar presión", "Dar masaje", "Hacer planos", "Programar código", "Diseñar logo", "Manejar avión", "Servir comida", "Manejar barco", "Bajar mina", "Forjar espada", "Coser botón", "Desfilar ropa", "Hacer malabares", "Entrenar equipo", "Cobrar falta", "Llevar palos", "Dar misa", "Escribir libro", "Leer noticias", "Editar video", "Filmar escena", "Cortar pelo", "Afeitar barba", "Hacer terapia", "Recetar remedio", "Analizar sangre", "Hacer experimento", "Mirar estrellas", "Excavar hueso", "Defender juicio", "Contar impuestos", "Depositar cheque", "Vender producto", "Firmar contrato", "Mandar mail", "Hacer reunión", "Despedir empleado", "Contratar gente", "Pedir aumento", "Renunciar trabajo", "Buscar trabajo", "Hacer currículum", "Tener entrevista", "Cobrar sueldo", "Pagar sueldo", "Hacer huelga", "Tomar examen", "Corregir prueba", "Borrar pizarrón", "Llamar lista", "Retar alumno", "Arrestar ladrón", "Patrullar calle", "Disparar arma", "Usar esposas", "Manejar patrulla", "Rescatar gato", "Salvar vida", "Hacer RCP", "Poner inyección", "Sacar sangre", "Coser herida", "Poner yeso", "Sacar radiografía", "Hacer ecografía", "Recetar lentes", "Arreglar caries", "Poner frenillos", "Hacer limpieza", "Anestesiar", "Sacar diente", "Hacer puente", "Poner corona", "Limpiar sarro", "Hacer consulta"]
    l2_en = ["Fighting fire", "Operating patient", "Directing traffic", "Pulling tooth", "Teaching math", "Cooking soup", "Fixing car", "Milking cow", "Taking photo", "Building wall", "Writing ticket", "Teaching reading", "Painting art", "Serving coffee", "Counting money", "Fixing pipe", "Sowing seeds", "Chopping wood", "Making dress", "Bridal makeup", "Checking BP", "Giving massage", "Drawing plans", "Coding", "Designing logo", "Flying plane", "Serving food", "Sailing boat", "Mining down", "Forging sword", "Sewing button", "Modeling clothes", "Juggling", "Coaching team", "Calling foul", "Carrying clubs", "Giving mass", "Writing book", "Reading news", "Editing video", "Filming scene", "Cutting hair", "Shaving beard", "Doing therapy", "Prescribing meds", "Analyzing blood", "Doing experiment", "Stargazing", "Digging bone", "Defending court", "Auditing tax", "Depositing check", "Selling product", "Signing contract", "Sending email", "Holding meeting", "Firing employee", "Hiring people", "Asking raise", "Quitting job", "Job hunting", "Making resume", "Interviewing", "Getting paid", "Paying wages", "Striking", "Examining", "Grading test", "Erasing board", "Roll call", "Scolding student", "Arresting thief", "Patrolling street", "Shooting gun", "Using cuffs", "Driving squad", "Rescuing cat", "Saving life", "Doing CPR", "Injecting shot", "Drawing blood", "Stitching wound", "Casting arm", "Xraying", "Ultrasound", "Rx glasses", "Fixing cavity", "Braces on", "Cleaning teeth", "Anesthetizing", "Extracting tooth", "Making bridge", "Crowning tooth", "Cleaning tartar", "Consulting"]
    
    while len(l2) < 100: l2.append("Job Extra L2 " + str(len(l2)))
    while len(l2_en) < 100: l2_en.append("Job Extra L2 " + str(len(l2_en)))
    l2 = l2[:100]; l2_en = l2_en[:100]

    for i in range(100): rows.append(["Profesiones", "Media", l2[i], l2_en[i]])

    l3 = ["Dentista miedo dientes", "Bombero miedo fuego", "Cirujano con hipo", "Mimo atrapado caja", "Astronauta flotando lejos", "Mago fallando truco", "Profesor perdiendo paciencia", "Policía persiguiendo tortuga", "Pintor manchado todo", "Juez golpeando dedo", "Payaso triste llorando", "Cocinero quemando agua", "Mecánico sobrando piezas", "Taxista perdido ciudad", "Piloto miedo volar", "Azafata tirando café", "Buzo sin aire", "Minero miedo oscuro", "Leñador hacha goma", "Sastre pinchando dedo", "Modelo cayendo pasarela", "Barbero cortando oreja", "Psicólogo durmiendo sesión", "Abogado perdiendo voz", "Contador perdiendo calculadora", "Banquero perdiendo llave", "Cajero dando dinero extra", "Vendedor tartamudo", "Gerente sin internet", "Dueño cerrando negocio", "Presidente olvidando discurso", "Cura olvidando rezo", "Monja bailando disco", "Escritor sin ideas", "Poeta sin rimas", "Periodista cámara apagada", "Director actor malo", "Camarógrafo lente tapa", "Sonidista ruido acople", "Maquillador payaso error", "Peluquero trasquilado", "Masajista mano fría", "Científico explosión lab", "Biólogo miedo bicho", "Químico bebiendo poción", "Astrónomo telescopio roto", "Historiador inventando datos", "Arqueólogo rompiendo momia", "Antropólogo tribu caníbal", "Albañil pared chueca", "Plomero inundando casa", "Gasista fuga gas", "Fletero rompiendo mueble", "Chofer chocando poste", "Capitán mareado barco", "Marinero nudo ciego", "Herrero quemando mano", "Granjero vaca escapa", "Jardinero cortando flores", "Cartero perro muerde", "Veterinario gato araña", "Arquitecto casa cae", "Fotógrafo dedo lente", "Electricista toque corriente", "Soldado casco revés", "Detective perdiendo pista", "Mozo tirando sopa", "Cantante gallo agudo", "Bailarín pantalón roto", "Actor olvidando línea", "Bibliotecario gritando silencio", "Guardaespaldas mosca molesta", "Salvavidas no sabe nadar", "Pescador bota anzuelo", "Cazador cazado trampa", "Torero toro corre", "Domador león come", "Trapecista red rota", "Mimo hablando celular", "Estatua viviente estornuda", "Malabarista tirando todo", "Títere hilos enredados", "Ventrílocuo moviendo boca", "Mago conejo muerde", "Payaso globo explota", "Acróbata marea vómito", "Presentador moco nariz", "Meteorólogo lluvia moja", "Basurero bolsa rota", "Barrendero viento hojas", "Limpiador vidrio cae", "Carnicero dedo corte", "Panadero quemando pan", "Lechero camión vuelca", "Pizzero pizza techo", "Heladero derrite todo", "Cartero carta equivocada", "Delivery pizza fría", "Taxista viaje largo"]
    l3_en = ["Dentist afraid teeth", "Firefighter fear fire", "Surgeon with hiccups", "Mime stuck box", "Astronaut floating away", "Magician failing trick", "Teacher losing patience", "Cop chasing turtle", "Painter messy all", "Judge hitting finger", "Sad clown crying", "Chef burning water", "Mechanic extra parts", "Taxi driver lost", "Pilot fear flying", "Stewardess spilling coffee", "Diver no air", "Miner fear dark", "Lumberjack rubber axe", "Tailor pricking finger", "Model falling runway", "Barber cutting ear", "Psychologist sleeping", "Lawyer losing voice", "Accountant lost calc", "Banker lost key", "Teller giving extra", "Salesman stuttering", "Manager no internet", "Owner closing shop", "Prez forgetting speech", "Priest forgot prayer", "Nun dancing disco", "Writer no ideas", "Poet no rhymes", "Journalist cam off", "Director bad actor", "Cameraman lens cap", "Soundman feedback noise", "Makeup clown error", "Hairdresser bad cut", "Masseur cold hand", "Scientist lab boom", "Biologist fear bug", "Chemist drinking potion", "Astronomer broken scope", "Historian fake facts", "Archaeologist breaking mummy", "Anthropologist cannibal tribe", "Mason crooked wall", "Plumber flooding house", "Gasman gas leak", "Mover breaking furniture", "Driver hitting pole", "Captain seasick", "Sailor bad knot", "Blacksmith burning hand", "Farmer cow escape", "Gardener cutting flowers", "Mailman dog bite", "Vet cat scratch", "Architect house fall", "Photog finger lens", "Electrician shock", "Soldier helmet backwards", "Detective losing cludel", "Waiter spilling soup", "Singer voice crack", "Dancer pants rip", "Actor forgot line", "Librarian yelling shh", "Bodyguard swatting fly", "Lifeguard cant swim", "Fisherman boot hook", "Hunter trapped own", "Matador bull chase", "Tamer lion eat", "Trapeze net broken", "Mime talking phone", "Statue sneezing", "Juggler dropping all", "Puppet tangled strings", "Ventrílocuo mouth move", "Magician rabbit bite", "Clown balloon pop", "Acrobat dizzy vomit", "Host snot nose", "Weatherman rain wet", "Garbage bag rip", "Sweeper wind leaves", "Cleaner falling glass", "Butcher finger cut", "Baker burning bread", "Milkman truck tip", "Pizza guy roof pizza", "Icecream melting all", "Mailman wrong letter", "Delivery cold pizza", "Taxi long ride"]
    
    while len(l3) < 100: l3.append("Job Extra L3 " + str(len(l3)))
    while len(l3_en) < 100: l3_en.append("Job Extra L3 " + str(len(l3_en)))
    l3 = l3[:100]; l3_en = l3_en[:100]

    for i in range(100): rows.append(["Profesiones", "Alta", l3[i], l3_en[i]])

    # ---------------- OBJETOS ----------------
    o_l1 = ["Celular", "Computadora", "Silla", "Mesa", "Cama", "Lámpara", "Reloj", "Espejo", "Lápiz", "Libro", "Tijeras", "Cuchara", "Tenedor", "Cuchillo", "Vaso", "Botella", "Llave", "Mochila", "Paraguas", "Escoba", "Estufa", "Horno", "Nevera", "Batidora", "Licuadora", "Tostadora", "Plancha", "Lavadora", "Secadora", "Aspiradora", "Trapeador", "Balde", "Esponja", "Jabón", "Champú", "Toalla", "Peine", "Cepillo", "Maquillaje", "Perfume", "Desodorante", "Pasta", "Hilo", "Aguja", "Botón", "Cierre", "Cinturón", "Corbata", "Zapato", "Media", "Pantalón", "Remera", "Camisa", "Vestido", "Pollera", "Guantes", "Bufanda", "Gorro", "Lentes", "Billetera", "Moneda", "Billete", "Tarjeta", "Bolsa", "Caja", "Regalo", "Juguete", "Muñeca", "Pelota", "Bicicleta", "Auto", "Moto", "Avión", "Barco", "Tren", "Semáforo", "Cartel", "Silla de ruedas", "Camilla", "Muletas", "Curita", "Remedio", "Jeringa", "Termómetro", "Estetoscopio", "Pizarrón", "Tiza", "Borrador", "Cuaderno", "Carpeta", "Regla", "Goma", "Sacapuntas", "Marcador", "Pincel", "Lienzo", "Martillo", "Clavo", "Destornillador", "Tornillo"]
    o_l1_en = ["Phone", "Computer", "Chair", "Table", "Bed", "Lamp", "Clock", "Mirror", "Pencil", "Book", "Scissors", "Spoon", "Fork", "Knife", "Glass", "Bottle", "Key", "Backpack", "Umbrella", "Broom", "Stove", "Oven", "Fridge", "Mixer", "Blender", "Toaster", "Iron", "Washer", "Dryer", "Vacuum", "Mop", "Bucket", "Sponge", "Soap", "Shampoo", "Towel", "Comb", "Brush", "Makeup", "Perfume", "Deodorant", "Paste", "Thread", "Needle", "Button", "Zipper", "Belt", "Tie", "Shoe", "Sock", "Pants", "T-shirt", "Shirt", "Dress", "Skirt", "Gloves", "Scarf", "Hat", "Glasses", "Wallet", "Coin", "Note", "Card", "Bag", "Box", "Gift", "Toy", "Doll", "Ball", "Bicycle", "Car", "Motorcycle", "Plane", "Boat", "Train", "Traffic light", "Sign", "Wheelchair", "Stretcher", "Crutches", "Band-aid", "Medicine", "Syringe", "Thermometer", "Stethoscope", "Board", "Chalk", "Eraser", "Notebook", "Folder", "Ruler", "Eraser", "Sharpener", "Marker", "Brush", "Canvas", "Hammer", "Nail", "Screwdriver", "Screw"]

    while len(o_l1) < 100: o_l1.append("Objeto Extra L1 " + str(len(o_l1)))
    while len(o_l1_en) < 100: o_l1_en.append("Item Extra L1 " + str(len(o_l1_en)))
    o_l1 = o_l1[:100]; o_l1_en = o_l1_en[:100]

    for i in range(100): rows.append(["Objetos", "Baja", o_l1[i], o_l1_en[i]])

    o_l2 = ["Abrir paraguas", "Escribir lápiz", "Cortar tijeras", "Leer libro", "Hablar celular", "Dormir cama", "Barrer piso", "Mirarse espejo", "Tomar vaso", "Abrir puerta", "Prender luz", "Apagar alarma", "Atar zapatos", "Ponerse lentes", "Peinarse pelo", "Lavarse dientes", "Secarse manos", "Planchar ropa", "Lavar platos", "Cocinar huevo", "Guardar mochila", "Sacar llave", "Pagar tarjeta", "Abrir regalo", "Inflar globo", "Tirar basura", "Regar planta", "Colgar cuadro", "Martillar clavo", "Atornillar mueble", "Cortar pan", "Servir agua", "Sonarse nariz", "Limpiar lentes", "Cambiar pilas", "Cargar celular", "Prender tele", "Cambiar canal", "Subir volumen", "Escuchar radio", "Tocar timbre", "Abrir carta", "Leer diario", "Firmar papel", "Pegar sticker", "Cortar uña", "Pintar labio", "Ponerse anillo", "Abrochar cinturón", "Subir cierre", "Abotonar camisa", "Ponerse gorro", "Sacarse guantes", "Doblar ropa", "Hacer cama", "Limpiar baño", "Baldear patio", "Sacudir alfombra", "Aspirar piso", "Trapear piso", "Lavar auto", "Inflar rueda", "Manejar bici", "Andar skate", "Patear pelota", "Tirar frisbee", "Volvuar barrilete", "Jugar cartas", "Tirar dados", "Armar puzzle", "Leer mapa", "Usar brújula", "Mirar binoculares", "Sacar foto", "Filmar video", "Tocar guitarra", "Tocar piano", "Tocar tambor", "Silbatos sonar", "Girar trompo", "Saltar soga", "Jugar yoyo", "Hacer burbujas", "Remontar barrilete", "Pintar dibujo", "Recortar papel", "Pegar figurita", "Escribir nombre", "Borrar error", "Sacar punta", "Medir regla", "Pesar balanza", "Tomar temperatura", "Poner curita", "Tomar pastilla", "Poner inyección", "Usar muletas", "Andar silla ruedas", "Manejar cochecito"]
    o_l2_en = ["Opening umbrella", "Writing pencil", "Cutting scissors", "Reading book", "Phone talk", "Sleeping bed", "Sweeping floor", "Looking mirror", "Drinking glass", "Opening door", "Light on", "Alarm off", "Tying shoes", "Glasses on", "Combing hair", "Brushing teeth", "Drying hands", "Ironing clothes", "Washing dishes", "Cooking egg", "Packing backpack", "Taking key", "Paying card", "Opening gift", "Inflating balloon", "Trash out", "Watering plant", "Hanging picture", "Hammering nail", "Screwing furniture", "Cutting bread", "Pouring water", "Blowing nose", "Cleaning glasses", "Changing batteries", "Charging phone", "TV on", "Channel change", "Volume up", "Radio listen", "Doorbell ring", "Opening letter", "Reading paper", "Signing paper", "Sticking sticker", "Cutting nail", "Lipstick on", "Ring on", "Buckling belt", "Zipping up", "Buttoning shirt", "Hat on", "Gloves off", "Folding clothes", "Making bed", "Cleaning bath", "Washing patio", "Shaking rug", "Vacuuming", "Mopping", "Car wash", "Tire pump", "Bike ride", "Skating", "Kicking ball", "Frisbee throw", "Kite fly", "Playing cards", "Rolling dice", "Puzzle solving", "Map reading", "Compass use", "Binoculars look", "Taking photo", "Filming video", "Guitar play", "Piano play", "Drum hit", "Whistle blow", "Top spin", "Rope jump", "Yoyo play", "Bubbles pop", "Kite flying", "Painting draw", "Paper cut", "Sticker paste", "Writing name", "Erasing error", "Sharpener use", "Ruler measure", "Scale weigh", "Temp taking", "Bandaid on", "Pill taking", "Injection giving", "Crutches use", "Wheelchair ride", "Stroller push"]

    while len(o_l2) < 100: o_l2.append("Objeto Extra L2 " + str(len(o_l2)))
    while len(o_l2_en) < 100: o_l2_en.append("Item Extra L2 " + str(len(o_l2_en)))
    o_l2 = o_l2[:100]; o_l2_en = o_l2_en[:100]

    for i in range(100): rows.append(["Objetos", "Media", o_l2[i], o_l2_en[i]])

    o_l3 = ["Lavadora caminando sola", "Tostadora quemando pan", "Paraguas dado vuelta", "Aspiradora tragando cortina", "Teléfono vibrando mesa", "Impresora atascada", "Inodoro desbordado", "Botella ketchup no sale", "Ventilador tirando papeles", "Silla rompe sentarse", "Microondas explotando huevo", "Licuadora sin tapa", "Plancha quemando camisa", "Secador pelo comiendo pelo", "Espejo roto mala suerte", "Reloj cucú loco", "Alarma no para sonar", "Llave rota cerradura", "Mochila agujereada cae todo", "Escoba voladora loca", "Estufa no prende", "Heladera descongelada agua", "Batidora salpicando masa", "Cuchillo sin filo", "Tenedor dientes doblados", "Cuchara sopera chica", "Vaso plástico volando viento", "Cama elásticos rotos", "Mesa pata corta", "Puerta rechina terror", "Lámpara titilando miedo", "Control remoto sin pilas", "Tele sin señal lluvia", "Bicicleta cadena salida", "Auto no arranca", "Moto pinchada lluvia", "Silla ruedas trabada", "Muletas resbalosas", "Curita no pega", "Jeringa aguja doblada", "Termómetro roto mercurio", "Pizarrón tiza chirría", "Marcador seco", "Lapiz punta rota 100 veces", "Goma mancha hoja", "Regla astillada", "Cuaderno espiral enganchado", "Carpeta anillos muerde", "Mochila cierre trabado", "Billetera vacía polilla", "Tarjeta rechazada", "Billete roto viento", "Moneda cae alcantarilla", "Bolsa rompe compras", "Regalo caja vacía", "Muñeca ojos miedo", "Pelota pincha vidrio", "Juguete pilas sulfatadas", "Soga salta enreda pies", "Jenga cae ruido", "Cartas vuelan viento", "Dados caen mesa", "Puzzle falta pieza", "Mapa roto lluvia", "Brújula imán loco", "Binoculares tapa puesta", "Cámara sin rollo memoria", "Guitarra cuerda corta", "Piano tecla desafinada", "Batería platillo cae", "Microfono acople agudo", "Parlante desconado", "Auriculares un lado anda", "Cargador cable corto", "Enchufe chispa susto", "Foco explota luz", "Vela quema mantel", "Florero agua podrida", "Alfombra tropiezo", "Cortina cae barral", "Persiana trabada chueca", "Ventana vidrio roto", "Puerta golpea dedo", "Candado llave perdida", "Cadena bici oxidada", "Timbre queda pegado", "Canilla gotea noche", "Ducha agua helada", "Inodoro tapa cae", "Papel higiénico fin", "Jabón resbala cae", "Toalla áspera lija", "Cepillo diente cae inodoro", "Pasta dientes tapa perdida", "Esponja vieja olor", "Trapo piso sucio", "Balde agujereado pierde", "Palita basura rompe"]
    o_l3_en = ["Washer walking alone", "Toaster burning bread", "Umbrella flipped wind", "Vacuum eating curtain", "Phone vibrating table", "Printer jamming", "Toilet overflowing", "Ketchup stuck bottle", "Fan blowing papers", "Chair breaking sit", "Microwave exploding egg", "Blender no lid", "Iron burning shirt", "Dryer eating hair", "Mirror broken luck", "Cuckoo clock crazy", "Alarm wont stop", "Key broken lock", "Backpack hole leak", "Broom flying crazy", "Stove wont light", "Fridge defrost leak", "Mixer splashing dough", "Knife dull blade", "Fork bent tines", "Spoon too small", "Cup flying wind", "Bed springs broken", "Table wobble leg", "Door squeak scary", "Lamp flickering fear", "Remote no battery", "TV static noise", "Bike chain off", "Car wont start", "Moto flat rain", "Wheelchair stuck", "Crutches slippery", "Bandaid no stick", "Syringe bent needle", "Thermometer broken", "Chalkboard screech", "Marker dry out", "Pencil break x100", "Eraser smudging", "Ruler splintered", "Notebook spiral snag", "Binder ring bite", "Zipper stuck bag", "Wallet empty moth", "Card declined", "Bill ripped wind", "Coin sewer drop", "Bag breaking grocery", "Gift empty box", "Doll scary eyes", "Ball breaking glass", "Toy battery acid", "Rope tangled feet", "Jenga crash loud", "Cards flying wind", "Dice falling table", "Puzzle missing piece", "Map torn rain", "Compass magnet crazy", "Binoculars cap on", "Camera no memory", "Guitar string snap", "Piano key dead", "Drum cymbal fall", "Mic feedback loud", "Speaker blown out", "Headphones one side", "Charger short cable", "Plug spark scare", "Bulb explode light", "Candle burn cloth", "Vase rotten water", "Rug trip hazard", "Curtain rod fall", "Blinds stuck crooked", "Window glass broke", "Door slam finger", "Padlock lost key", "Chain bike rust", "Doorbell stuck on", "Faucet drip night", "Shower ice cold", "Toilet seat slam", "Toilet paper out", "Soap slip fall", "Towel sandpaper", "Brush toilet drop", "Toothpaste cap lost", "Sponge old smell", "Rag dirty floor", "Bucket leak hole", "Dustpan handle break"]

    while len(o_l3) < 100: o_l3.append("Objeto Extra L3 " + str(len(o_l3)))
    while len(o_l3_en) < 100: o_l3_en.append("Item Extra L3 " + str(len(o_l3_en)))
    o_l3 = o_l3[:100]; o_l3_en = o_l3_en[:100]

    for i in range(100): rows.append(["Objetos", "Alta", o_l3[i], o_l3_en[i]])

    # ---------------- COMIDA ----------------
    c_l1 = ["Pizza", "Hamburguesa", "Helado", "Taco", "Sushi", "Sopa", "Chocolate", "Banana", "Manzana", "Huevo", "Pan", "Queso", "Carne", "Pollo", "Pescado", "Fideos", "Ensalada", "Torta", "Jugo", "Café", "Sandía", "Naranja", "Uva", "Frutilla", "Limón", "Pera", "Durazno", "Cereza", "Melón", "Piña", "Coco", "Kiwi", "Mandarina", "Pomelo", "Ciruela", "Higo", "Palta", "Tomate", "Lechuga", "Papa", "Cebolla", "Ajo", "Zanahoria", "Choclo", "Zapallo", "Espinaca", "Brócoli", "Coliflor", "Pepino", "Arroz", "Lentejas", "Porotos", "Garbanzos", "Maíz", "Trigo", "Avena", "Harina", "Azúcar", "Sal", "Aceite", "Vinagre", "Pimienta", "Orégano", "Canela", "Vainilla", "Miel", "Mermelada", "Manteca", "Crema", "Yogur", "Leche", "Agua", "Soda", "Gaseosa", "Vino", "Cerveza", "Té", "Mate", "Jamon", "Salame", "Panceta", "Salchicha", "Chorizo", "Morcilla", "Asado", "Milanesa", "Empanada", "Tamal", "Burrito", "Nachos", "Guacamole", "Paella", "Ravioles", "Ñoquis", "Lasaña", "Canelones", "Tarta", "Alfajor", "Churros", "Donas"]
    c_l1_en = ["Pizza", "Burger", "IceCream", "Taco", "Sushi", "Soup", "Chocolate", "Banana", "Apple", "Egg", "Bread", "Cheese", "Meat", "Chicken", "Fish", "Noodles", "Salad", "Cake", "Juice", "Coffee", "Watermelon", "Orange", "Grape", "Strawberry", "Lemon", "Pear", "Peach", "Cherry", "Melon", "Pineapple", "Coconut", "Kiwi", "Tangerine", "Grapefruit", "Plum", "Fig", "Avocado", "Tomato", "Lettuce", "Potato", "Onion", "Garlic", "Carrot", "Corn", "Pumpkin", "Spinach", "Broccoli", "Cauliflower", "Cucumber", "Rice", "Lentils", "Beans", "Chickpeas", "Maize", "Wheat", "Oats", "Flour", "Sugar", "Salt", "Oil", "Vinegar", "Pepper", "Oregano", "Cinnamon", "Vanilla", "Honey", "Jam", "Butter", "Cream", "Yogur", "Milk", "Water", "Soda", "Pop", "Wine", "Beer", "Tea", "Mate", "Ham", "Salami", "Bacon", "Sausage", "Chorizo", "BloodSausage", "BBQ", "Schnitzel", "Empanada", "Tamale", "Burrito", "Nachos", "Guacamole", "Paella", "Ravioli", "Gnocchi", "Lasagna", "Cannelloni", "Pie", "Alfajor", "Churros", "Donuts"]

    while len(c_l1) < 100: c_l1.append("Comida Extra L1 " + str(len(c_l1)))
    while len(c_l1_en) < 100: c_l1_en.append("Food Extra L1 " + str(len(c_l1_en)))
    c_l1 = c_l1[:100]; c_l1_en = c_l1_en[:100]

    for i in range(100): rows.append(["Comida", "Baja", c_l1[i], c_l1_en[i]])
    
    # L2 Comida
    c_l2 = ["Comer fideos", "Cortar carne", "Pelar banana", "Lamer helado", "Hacer sandwich", "Revolver sopa", "Romper huevo", "Tomar café", "Salar comida", "Mascar chicle", "Batir crema", "Amasar pan", "Freír papas", "Hervir agua", "Cortar torta", "Servir vino", "Brindar copas", "Soplar vela", "Poner mesa", "Lavar fruta", "Exprimir jugo", "Rallar queso", "Untar dulce", "Picar cebolla", "Llorar cebolla", "Quemar tostada", "Derretir queso", "Enfriar sopa", "Comer taco", "Usar palitos", "Cortar pizza", "Tomar mate", "Cebar mate", "Hacer asado", "Prender carbón", "Dar vuelta carne", "Pinchar chorizo", "Servir ensalada", "Condimentar", "Probar salsa", "Soplar caliente", "Chupar limón", "Morder manzana", "Escupir carozo", "Pelar naranja", "Comer uvas", "Sacar semillas", "Limpiar pescado", "Deshuesar pollo", "Rellenar pavo", "Hornear galletas", "Decorar torta", "Poner velitas", "Cortar porciones", "Repartir comida", "Pedir cuenta", "Dejar propina", "Leer menú", "Elegir plato", "Esperar comida", "Tener hambre", "Tener sed", "Estar lleno", "Repetir plato", "Guardar sobras", "Calentar microondas", "Abrir lata", "Destapar botella", "Sacar corcho", "Servir hielo", "Mezclar bebida", "Agitar coctel", "Tomar sorbete", "Hacer burbujas", "Comer pochoclo", "Mirar peli comer", "Comer en cama", "Desayunar cama", "Hacer picnic", "Comer pasto", "Comer arena", "Tragar semilla", "Morder lengua", "Quemar lengua", "Congelar cerebro", "Manchar ropa", "Usar servilleta", "Limpiar boca", "Eructar fuerte", "Tener hipo", "Usar escarbadientes", "Masticar hielo", "Chupar hueso", "Dejar borde pizza", "Comer borde pizza", "Robar papas frita", "Compartir postre", "Pedir postre", "Tomar café doble"]
    c_l2_en = ["Eating noodles", "Cutting meat", "Peeling banana", "Licking icecream", "Making sandwich", "Stirring soup", "Cracking egg", "Drinking coffee", "Salting food", "Chewing gum", "Whipping cream", "Kneading bread", "Frying fries", "Boiling water", "Cutting cake", "Pouring wine", "Toasting glasses", "Blowing candle", "Setting table", "Washing fruit", "Squeezing juice", "Grating cheese", "Spreading jam", "Chopping onion", "Crying onion", "Burning toast", "Melting cheese", "Cooling soup", "Eating taco", "Using chopsticks", "Cutting pizza", "Drinking mate", "Serving mate", "Making BBQ", "Lighting coal", "Flipping meat", "Poking sausage", "Serving salad", "Seasoning", "Tasting sauce", "Blowing hot", "Sucking lemon", "Biting apple", "Spitting pit", "Peeling orange", "Eating grapes", "Removing seeds", "Cleaning fish", "Deboning chicken", "Stuffing turkey", "Baking cookies", "Decorating cake", "Placing candles", "Cutting slices", "Sharing food", "Asking check", "Leaving tip", "Reading menu", "Picking dish", "Waiting food", "Being hungry", "Being thirsty", "Being full", "Second helping", "Saving leftovers", "Microwaving", "Opening can", "Uncapping bottle", "Uncorking", "Serving ice", "Mixing drink", "Shaking cocktail", "Sipping straw", "Blowing bubbles", "Eating popcorn", "Movie snacking", "Bed eating", "Bed breakfast", "Picnic time", "Eating grass", "Eating sand", "Swallowing seed", "Biting tongue", "Burning tongue", "Brain freeze", "Staining clothes", "Using napkin", "Wiping mouth", "Burping loud", "Having hiccups", "Using toothpick", "Chewing ice", "Sucking bone", "Leaving crust", "Eating crust", "Stealing fry", "Sharing dessert", "Ordering cake", "Double espresso"]

    while len(c_l2) < 100: c_l2.append("Comida Extra L2 " + str(len(c_l2)))
    while len(c_l2_en) < 100: c_l2_en.append("Food Extra L2 " + str(len(c_l2_en)))
    c_l2 = c_l2[:100]; c_l2_en = c_l2_en[:100]

    for i in range(100): rows.append(["Comida", "Media", c_l2[i], c_l2_en[i]])
    
    # L3 Comida
    c_l3 = ["Comer gelatina tenedor", "Morder limón ácido", "Espagueti sin manos", "Helado cae suelo", "Quemar lengua café", "Tragar semilla sandía", "Llorar picando cebolla", "Comer ají picante", "Abrir coco dientes", "Globo chicle explota", "Explota huevo microondas", "Ketchup no sale", "Tapa salero suelta", "Mosca en la sopa", "Pelo en la comida", "Pan duro piedra", "Galleta cae leche", "Hielo cae piso", "Soda sale nariz", "Manchar camisa salsa", "Pizza cae boca abajo", "Fideos nariz risa", "Mordiendo tenedor fuerte", "Diente roto hueso", "Espinaca diente foto", "Semilla diente molesta", "Hipo por comer rápido", "Cerebro congelado helado", "Lengua pegada hielo", "Caramelo pegado muela", "Chicle pegado pelo", "Pochoclo diente trabado", "Tomate explota mordida", "Alfajor aplastado mochila", "Banana negra mochila", "Manzana con gusano", "Huevo podrido olor", "Leche vencida agria", "Pan con moho verde", "Fruta plástico morder", "Torta cumpleaños piso", "Poner sal en vez azúcar", "Quemar arroz olla", "Fideos pegados olla", "Agua hierve vuelca", "Aceite salpica ojo", "Cortarse dedo lata", "Romper copa brindis", "Corcho dentro botella", "Volcar vino mantel", "Restaurante tarjeta rechazada", "Olvidar billetera cena", "Mozo tira comida encima", "Plato caliente quema mano", "Vaso resbala rompe", "Sorbete agujereado no anda", "Burbujas nariz gaseosa", "Comiendo con boca abierta", "Hablando con boca llena", "Escupir comida risa", "Ahogarse con miga", "Toser polvo canela", "Estornudar harina cara", "Huevo cabeza rompe", "Tomatazo en la cara", "Tortazo en la cara", "Guerra de comida", "Resbalar cáscara banana", "Pisar uva vino", "Exprimir naranja ojo", "Cortar dedo cuchillo", "Quemar mano horno", "Comer sushi palitos difícil", "Mayonesa explota pomo", "Mostaza mancha remera", "Dulce leche pegoteado", "Miel pegoteada todo", "Chocolate derretido bolsillo", "Chupetín pegado sábana", "Galleta cama migas", "Comer hormiga sin querer", "Tragar mosca vino", "Pájaro roba sandwich", "Perro roba asado", "Gato camina mesa", "Pelo gato plato", "Vaso térmico pierde", "Café frío horrible", "Mate lavado feo", "Bombilla tapada yerba", "Termo roto vidrio", "Agua mate hirviendo", "Quemar lengua pizza", "Queso estira infinito", "Hamburguesa desarma toda", "Taco rompe abajo", "Salsa cae pantalón", "Helado derrite mano", "Cucurucho roto abajo"]
    c_l3_en = ["Jelly with fork", "Biting sour lemon", "Spaghetti no hands", "Icecream drop floor", "Coffee tongue burn", "Swallow watermelon seed", "Crying onion chop", "Eating hot chili", "Open coco teeth", "Gum bubble pop", "Egg explode microwave", "Ketchup stuck bottle", "Salt cap loose", "Fly in soup", "Hair in food", "Rock hard bread", "Cookie drop milk", "Ice drop floor", "Soda nose spray", "Sauce stain shirt", "Pizza face down", "Noodle nose laugh", "Biting fork hard", "Tooth chip bone", "Spinach tooth photo", "Seed stuck tooth", "Hiccups eating fast", "Brain freeze ice", "Tongue stuck ice", "Candy stuck molar", "Gum stuck hair", "Popcorn stuck tooth", "Tomato explode bite", "Smashed backpack cookie", "Black banana bag", "Apple with worm", "Rotten egg smell", "Sour milk expir.", "Green mold bread", "Biting plastic fruit", "Bday cake floor", "Salt instead sugar", "Burnt rice pot", "Stuck pasta pot", "Water boil over", "Oil splash eye", "Finger cut can", "Toast glass break", "Cork inside bottle", "Wine spill cloth", "Card declined dinner", "Forgot wallet meal", "Waiter spill food", "Hot plate burn", "Glass slip break", "Hole straw fail", "Soda nose bubbles", "Open mouth eating", "Full mouth talking", "Spit food laugh", "Choking on crumb", "Cinnamon cough dust", "Flour face sneeze", "Egg head crack", "Tomato face hit", "Pie face hit", "Food fight mess", "Banana peel slip", "Grape stomp wine", "Orange juice eye", "Knife finger cut", "Oven hand burn", "Sushi chopstick fail", "Mayo explode tube", "Mustard stain shirt", "Sticky caramel mess", "Honey sticky all", "Melted choc pocket", "Lollipop stuck sheet", "Cookie bed crumbs", "Eating ant accident", "Swallow fly wine", "Bird steals sandwich", "Dog steals bbq", "Cat walks table", "Cat hair plate", "Travel mug leak", "Cold coffee yuck", "Washed out mate", "Straw clogged herb", "Thermos glass break", "Boiling mate water", "Pizza tongue burn", "Cheese stretch infinite", "Burger falls apart", "Taco break bottom", "Salsa drop pants", "Icecream melt hand", "Cone break bottom"]

    while len(c_l3) < 100: c_l3.append("Comida Extra L3 " + str(len(c_l3)))
    while len(c_l3_en) < 100: c_l3_en.append("Food Extra L3 " + str(len(c_l3_en)))
    c_l3 = c_l3[:100]; c_l3_en = c_l3_en[:100]

    for i in range(100): rows.append(["Comida", "Alta", c_l3[i], c_l3_en[i]])
    
    # ---------------- FIESTA ----------------
    f_l1 = ["Globo", "Torta", "Regalo", "Piñata", "Vela", "Disfraz", "Música", "Baile", "Confeti", "Bebida", "Payaso", "Invitación", "Sorpresa", "Foto", "Amigos", "Familia", "Cumpleaños", "Navidad", "Año Nuevo", "Boda", "Anillo", "Vestido", "Traje", "DJ", "Luces", "Karaoke", "Juegos", "Sillas", "Mesa", "Comida", "Dulces", "Caramelos", "Chupetín", "Galletas", "Sandwich", "Pizza", "Gaseosa", "Jugo", "Vaso", "Plato", "Servilleta", "Cuchara", "Tenedor", "Cuchillo", "Mantel", "Adorno", "Guirnalda", "Cartel", "Banderín", "Bonete", "Silbato", "Matraca", "Espuma", "Serpentina", "Antifaz", "Peluca", "Maquillaje", "Nariz", "Zapatos", "Magia", "Truco", "Mago", "Animador", "Burbujas", "Humor", "Risa", "Aplauso", "Abrazo", "Beso", "Brindis", "Copa", "Botella", "Hielo", "Baile", "Vals", "Trencito", "Cumbia", "Rock", "Pop", "Salsa", "Regalo", "Moño", "Papel", "Cinta", "Tarjeta", "Sobre", "Dinero", "Juguete", "Ropa", "Libro", "Perfume", "Reloj", "Celular", "Cámara", "Video", "Micrófono", "Parlante", "Escenario", "Telón"]
    f_l1_en = ["Balloon", "Cake", "Gift", "Piñata", "Candle", "Costume", "Music", "Dance", "Confetti", "Drink", "Clown", "Invitation", "Surprise", "Photo", "Friends", "Family", "Birthday", "Christmas", "New Year", "Wedding", "Ring", "Dress", "Suit", "DJ", "Lights", "Karaoke", "Games", "Chairs", "Table", "Food", "Sweets", "Candy", "Lollipop", "Cookies", "Sandwich", "Pizza", "Soda", "Juice", "Cup", "Plate", "Napkin", "Spoon", "Fork", "Knife", "Tablecloth", "Ornament", "Garland", "Poster", "Banner", "Party Hat", "Whistle", "Noisemaker", "Foam", "Streamer", "Mask", "Wig", "Makeup", "Nose", "Shoes", "Magic", "Trick", "Magician", "Entertainer", "Bubbles", "Humor", "Laugh", "Clap", "Hug", "Kiss", "Toast", "Glass", "Bottle", "Ice", "Dance", "Waltz", "Conga", "Cumbia", "Rock", "Pop", "Salsa", "Gift", "Bow", "Paper", "Ribbon", "Card", "Envelope", "Money", "Toy", "Clothes", "Book", "Perfume", "Watch", "Phone", "Camera", "Video", "Mic", "Speaker", "Stage", "Curtain"]

    while len(f_l1) < 100: f_l1.append("Fiesta Extra L1 " + str(len(f_l1)))
    while len(f_l1_en) < 100: f_l1_en.append("Party Extra L1 " + str(len(f_l1_en)))
    f_l1 = f_l1[:100]; f_l1_en = f_l1_en[:100]

    for i in range(100): rows.append(["Fiesta", "Baja", f_l1[i], f_l1_en[i]])
    
    f_l2 = ["Soplar velas", "Abrir regalo", "Romper piñata", "Bailar abuela", "Inflar globos", "Servir torta", "Sacar selfie", "Brindar copas", "Poner música", "Jugar sillas", "Cantar feliz cumple", "Comer torta", "Tomar gaseosa", "Tirar confeti", "Usar bonete", "Tocar trompeta", "Hacer magia", "Contar chiste", "Reír fuerte", "Aplaudir mucho", "Dar abrazo", "Dar beso", "Bailar vals", "Hacer trencito", "Saltar música", "Gritar sorpresa", "Esconderse puerta", "Apagar luz", "Prender luz", "Llegar tarde", "Irse temprano", "Lavar platos", "Juntar basura", "Barrer piso", "Limpiar mesa", "Guardar sillas", "Despedir gente", "Saludar gente", "Presentar amigo", "Conocer gente", "Hablar mucho", "Comer mucho", "Beber mucho", "Dormir sofá", "Perder celular", "Romper copa", "Manchar ropa", "Perder zapato", "Desatar moño", "Leer tarjeta", "Contar dinero", "Usar juguete", "Probar ropa", "Oler perfume", "Mirar reloj", "Sacar foto", "Filmar video", "Usar microfono", "Cantar karaoke", "Bailar lento", "Bailar rock", "Mover esqueleto", "Hacer pogo", "Saltar soga", "Jugar estatua", "Jugar escondidas", "Jugar mancha", "Jugar cartas", "Hacer trampa", "Ganar premio", "Perder juego", "Estar feliz", "Estar cansado", "Tener sueño", "Tener hambre", "Tener sed", "Hacer pis", "Cambiar pañal", "Dormir bebé", "Cuidar perro", "Sacar perro", "Fumar afuera", "Pedir taxi", "Manejar auto", "Caminar casa", "Subir escalera", "Bajar escalera", "Tocar timbre", "Abrir puerta", "Cerrar puerta", "Perder llave", "Buscar llave", "Llamar taxi", "Esperar bus", "Tomar bondi", "Caminar calle", "Mirar luna", "Pedir deseo", "Soplar deseo"]
    f_l2_en = ["Blowing candles", "Opening gift", "Breaking piñata", "Dancing grandma", "Inflating balloons", "Serving cake", "Taking selfie", "Toasting glasses", "Playing music", "Playing chairs", "Singing bday", "Eating cake", "Drinking soda", "Throwing confetti", "Wearing hat", "Blowing trumpet", "Doing magic", "Telling joke", "Laughing loud", "Clapping hard", "Giving hug", "Giving kiss", "Dancing waltz", "Doing conga", "Jumping music", "Yelling surprise", "Hiding door", "Lights off", "Lights on", "Arriving late", "Leaving early", "Washing dishes", "Collecting trash", "Sweeping floor", "Cleaning table", "Storing chairs", "Saying goodbye", "Greeting people", "Intro friend", "Meeting people", "Talking much", "Eating much", "Drinking much", "Sleeping sofa", "Losing phone", "Breaking glass", "Stain clothes", "Losing shoe", "Untying bow", "Reading card", "Counting money", "Using toy", "Trying clothes", "Smelling perfume", "Checking watch", "Taking photo", "Filming video", "Using mic", "Karaoke sing", "Slow dance", "Rock dance", "Shaking bones", "Moshing", "Rope jump", "Statue game", "Hide seek", "Tag game", "Card game", "Cheating", "Winning prize", "Losing game", "Being happy", "Being tired", "Being sleepy", "Being hungry", "Being thirsty", "Peeing", "Diaper change", "Baby sleep", "Dog sitting", "Dog walking", "Smoking out", "Calling taxi", "Driving car", "Walking home", "Stairs up", "Stairs down", "Ringing bell", "Opening door", "Closing door", "Losing key", "Finding key", "Calling cab", "Waiting bus", "Taking bus", "Walking street", "Looking moon", "Making wish", "Blowing wish"]

    while len(f_l2) < 100: f_l2.append("Fiesta Extra L2 " + str(len(f_l2)))
    while len(f_l2_en) < 100: f_l2_en.append("Party Extra L2 " + str(len(f_l2_en)))
    f_l2 = f_l2[:100]; f_l2_en = f_l2_en[:100]

    for i in range(100): rows.append(["Fiesta", "Media", f_l2[i], f_l2_en[i]])
    
    f_l3 = ["Caerse sobre torta", "Payaso pierde zapatos", "Cantar desafinado", "Piñata no rompe", "Recibir regalo feo", "Quedarse encerrado baño", "Dormirse en fiesta", "Volcar bebida vestido", "Bailar conga solo", "DJ música equivocada", "Novia cae al agua", "Novio pierde anillo", "Torta cae piso", "Perro come torta", "Vela quema pelo", "Globo explota cara", "Confeti en ojo", "Zapato vuela baile", "Pantalón roto agacharse", "Camisa manchada vino", "Vomitar en arbusto", "Pelea por centro mesa", "Tío borracho bailando", "Abuela perdiendo dientes", "Niño llorando payaso", "Mago falla truco", "Conejo escapa galera", "Paloma caga novio", "Lluvia arruina fiesta", "Carpa se vuela", "Viento lleva mantel", "Silla plástico rompe", "Mesa cae comida", "Luz se corta", "Música se corta", "Microfono acopla fuerte", "Parlante explota", "Vecino llama policía", "Policía para fiesta", "Auto remolcado grúa", "Perder llaves auto", "Olvidar regalo casa", "Regalar caja vacía", "Tarjeta nombre equivocado", "Confundir cumpleañero", "Saludar desconocido", "Besar persona equivocada", "Tirar bebida otro", "Romper vaso brindis", "Corcho pega ojo", "Espuma nieve ojo", "Resbalar pista baile", "Caerse escenario", "Tropezar vestido novia", "Pisar cola vestido", "Romper cierre vestido", "Perder zapato cenicienta", "Quedarse sin voz", "Dolor pies tacos", "Dormir silla rincón", "Roncar en fiesta", "Babear almohadón sofá", "Despertar cara pintada", "Perder billetera fiesta", "Perder celular baño", "Caer piscina ropa", "Tirar a la piscina", "Nadar en la fuente", "Robar centro mesa", "Llevarse comida bolso", "Comer sobras otro", "Tomar vaso otro", "Confundir vaso", "Tomar agua florero", "Comer flor adorno", "Morder vela torta", "Soplar vela otro", "Escupir torta soplar", "Estornudar sobre torta", "Toser en comida", "Mancharse chocolate", "Helado derretido mano", "Pegoteado dulce", "Chicle pegado pelo", "Pisar chicle nuevo", "Romper piñata cabeza", "Palo piñata golpe", "Caramelos golpean cara", "Niños pisan buscando", "Llorar no ganar", "Enojo perder juego", "Hacer trampa obvia", "Ser descubierto trampa", "Pelea por silla", "Caer silla juego", "Música muy fuerte", "Dolor cabeza ruido", "Irse sin saludar"]
    f_l3_en = ["Falling on cake", "Clown losing shoes", "Singing off key", "Piñata wont break", "Getting ugly gift", "Locked in bathroom", "Sleeping at party", "Spilling drink dress", "Dancing conga alone", "DJ wrong music", "Bride falling water", "Groom losing ring", "Cake dropping floor", "Dog eating cake", "Candle burning hair", "Balloon pop face", "Confetti in eye", "Shoe flying dance", "Pants rip squat", "Shirt wine stain", "Vomit in bush", "Fight centerpiece", "Drunk uncle dancing", "Grandma losing teeth", "Kid crying clown", "Magician fail trick", "Rabbit escape hat", "Pigeon poop groom", "Rain ruining party", "Tent flying away", "Wind blowing cloth", "Plastic chair break", "Table food fall", "Power outage", "Music cut off", "Mic feedback loud", "Speaker explode", "Neighbor calls cops", "Police stop party", "Car towed away", "Losing car keys", "Forgot gift home", "Giving empty box", "Card wrong name", "Confusing bday boy", "Greeting stranger", "Kissing wrong person", "Spilling drink other", "Breaking toast glass", "Cork hit eye", "Foam spray eye", "Slip dance floor", "Fall off stage", "Trip bride dress", "Step dress train", "Break dress zipper", "Lose cinderella shoe", "Losing voice", "Sore feet heels", "Sleeping chair corner", "Snoring at party", "Drooling sofa pillow", "Wake painted face", "Lose wallet party", "Lose phone toilet", "Fall pool clothes", "Throwing in pool", "Swim in fountain", "Stealing centerpiece", "Taking food purse", "Eating leftovers", "Drinking others cup", "Confusing cup", "Drinking vase water", "Eating flower decor", "Biting cake candle", "Blowing other candle", "Spit cake blow", "Sneeze on cake", "Cough on food", "Choc stain face", "Melted icecream hand", "Sticky sweet mess", "Gum stuck hair", "Step gum new shoe", "Break piñata head", "Piñata stick hit", "Candy hit face", "Kids stampede", "Crying no win", "Angry losing game", "Cheating obvious", "Caught cheating", "Fight for chair", "Fall chair game", "Music too loud", "Headache noise", "Irish goodbye"]

    while len(f_l3) < 100: f_l3.append("Fiesta Extra L3 " + str(len(f_l3)))
    while len(f_l3_en) < 100: f_l3_en.append("Party Extra L3 " + str(len(f_l3_en)))
    f_l3 = f_l3[:100]; f_l3_en = f_l3_en[:100]

    for i in range(100): rows.append(["Fiesta", "Alta", f_l3[i], f_l3_en[i]])
    
    return rows

if __name__ == "__main__":
    data = get_data()
    with open('db_part4.csv', 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f); writer.writerow(['Categoría', 'Nivel', 'Español (Latino)', 'Inglés']); writer.writerows(data)
